### ISSUE TITLE
'shared' is unavailable in application extensions for ios

### ISSUE THREAD

**Issue by superphil0** [customerio/customerio-reactnative#102]
**SDK version:** 
2.1.0

**Describe the issue**
When trying to build 2.1.0 into our app, I get this error
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

**Screenshots**
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/1478557/221199661-b28a06f7-63a6-4bfc-9bb5-2cf4a21650a5.png">

**Additional context**
When I set the setting: "require only app-extension-safe API" to false inside the Pod CustomerIOCommon, the app builds fine

Is there anything I can change to make this go away, as it is breaking our builds
br

**Comment by Allanbcruz** [comment]
### Environment and Version:
processor: Apple M2
customerio-reactnative: "3.1.8",
react: "18.2.0",
react-native: "0.71.7",

### Describe the issue:
When I try to build version 3.1.8 I get the following error:
**_'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead._**

### Screenshots

![Captura de Tela 2023-08-31 às 13 52 53](https://github.com/customerio/customerio-reactnative/assets/57270969/05d6b8dd-51ff-48d6-8e26-45a52ee241a7)

### Additional context
I followed all the setup mentioned in the documentation https://customer.io/docs/sdk/react-native/push-notifications/push/

**Comment by luihugo** [comment]
hoe did you solve this @superphil0  @Allanbcruz
