### ISSUE TITLE
Add ability to provide safe area to in app messages

### ISSUE THREAD

**Issue by vanenshi** [customerio/customerio-reactnative#108]
**Is your feature request related to a problem? Please describe.**

When we are using in-app messages, the modal is stuck to the top of the device (especially in ios) and makes it impossible 
to press the dismiss button

**Describe the solution you'd like**

be able to provide a `portal` or `view` globally for the in-app messages

**Comment by lj-cio** [comment]
Hi @vanenshi, thanks for writing in!  To help our team troubleshoot, could you share a screenshot of what you're seeing and a link to the message in your CIO workspace?  You can also send these to product@customer.io and reference this issue if that's preferable.

**Comment by vanenshi** [comment]
I am using the example welcome: https://fly.customer.io/env/128619/in-app-messages/example-welcome
This image is from iOS, as you can see, the close button is in a bad position
<img src="https://user-images.githubusercontent.com/61600246/224045971-e18d3864-1bdd-430d-88cf-e082edbdf64a.png" width="300">


also take a look at this one https://fly.customer.io/env/128619/in-app-messages/example-banner
<img src="https://user-images.githubusercontent.com/61600246/224046162-ed2a24c7-c538-492e-942d-0ab8eccf47f4.png" width="300">

I know there are workarounds for this, like using a big amount of padding, but we like to have the same view for in-app messages in iOS and Android
So a preferable method would be able to pass the wrapper (container) component for the in-app message. by doing so, we can adjust the safe area View for the component.

**Comment by lj-cio** [comment]
@vanenshi Thanks for sending the examples over.  Apologies for the delay in responding-- I confirmed the recommended workaround for now is using padding, but have shared your examples and upvoted a more configurable option for the team to investigate.  

I'm closing this issue for now, but please reopen if you have questions or additional feedback on this!
