### ISSUE TITLE
Sending null param on identify

### ISSUE THREAD

**Issue by serdargun** [customerio/customerio-reactnative#112]
SDK version:
Customerio-reactnative: ^2.0.0-beta.1
React Native: 0.64.4

We may have some `null` people params as in the example below. When we want to send this object its not working because of `null` value. It took me a long time to detect where the mistake was. I can kindly suggest that you can use type conversion for `null` values like `null` to `string`. Filtering user params for `null` values also takes time. 

`CustomerIO.identify("person@example.com", {first_name: 'Lorem', last_name: 'Ipsum', phone_number: null})`

**Comment by StephMoreno** [comment]
Hi @serdargun, 

I'm Stephanie, a Product Manager here. I wanted to get a little more information from you on this request. 

- Can you provide some context around your use case so we can better understand?
- Are you saying that if at least one of your params is null, that the entire identify call fails?

Lastly, we currently don't allow this as a string to intentionally not make the assumption on behalf of all our customers. Our engineers recommend this be handled on your end. Is this something you've considered?
