### ISSUE TITLE
Pod version conflicts 

### ISSUE THREAD

**Issue by scottwio** [customerio/customerio-reactnative#125]
**SDK version:**
customerio-reactnative = 2.3.2

**Environment:** Development or Production
Production

**Describe the bug**
I have followed your instructions here https://customer.io/docs/sdk/react-native/push/ to get customer.io setup with react-native and FCM. As part of the instructions, it says to install the MessagingPushFCM pod ` pod 'CustomerIO/MessagingPushFCM', '~> 2.3.0` however, when I do so, this conflicts with the pod dependencies in `/node_modules/customerio-reactnative/customerio-reactnative.podspec` I've attached the error message. I solved this by using 2.1.0 of the MessagingPushFCM which works `pod 'CustomerIO/MessagingPushFCM', '2.1.0'` but it would be good to know this is the blessed method.

**Screenshots**

![Screenshot 2023-04-26 at 16 14 49](https://user-images.githubusercontent.com/340168/234621510-a1678147-540e-4766-8900-9b2c71746013.jpg)

**Comment by Shahroz16** [comment]
Hey @scottwio, thanks for writing in. Apologies for the inconvenience, we are fixing this. 

Meanwhile, I believe if you were to delete their `Podfile.lock` and run `pod update --repo-update`. 

It might solve the issue.

**Comment by scottwio** [comment]
> Hey @scottwio, thanks for writing in. Apologies for the inconvenience, we are fixing this.
> 
> Meanwhile, I believe if you were to delete their `Podfile.lock` and run `pod update --repo-update`.
> 
> It might solve the issue.

I did try this a couple of times without any luck

**Comment by levibostian** [comment]
Thank you for reporting this issue to us, @scottwio. Sorry to hear that you are experiencing an issue with the SDK. 

We have a [bug fix](https://github.com/customerio/customerio-reactnative/pull/124) currently going through testing to fix this problem that you are experiencing. 

Until that bug fix gets shipped in a future version of the React Native SDK, a temporary workaround is to use this in your `Podfile`:

```ruby
pod 'CustomerIO/MessagingPushFCM', '~> 2.1.0
```

which, you mentioned worked for you.

**Comment by levibostian** [comment]
I'm going to close this issue since there is a fix shipped. If the issue still exists, we can re-open the issue.
