### ISSUE TITLE
How do I get push token from SDK ?

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-reactnative#127]
**Describe the issue**
I need to access push token from the SDK. Is there a method to do so ?

**Comment by mrehan27** [comment]
Hi @jbtheard. We don't currently expose any method to fetch push token. Can you please explain your use-case why do you need to fetch the token?

**Comment by jbtheard** [comment]
I use a MMP tool ([Adjust](https://help.adjust.com/en/article/push-tokens-android-sdk#)) that requires tokens to be sent with events in order to build audiences and track uninstalls.
This is a must have.

As I'm using Expo, perhaps I should use [expo-notifications](https://docs.expo.dev/versions/latest/sdk/notifications/) to get that in the meanwhile ? Would that be compatible ?

**Comment by mrehan27** [comment]
Yes, `expo-notifications` might help you get the desired token. But unfortunately, since there are already a few [issues were reported with `expo-notifications`](https://github.com/customerio/customerio-expo-plugin/issues/68), you'll have to wait till expo issue is fixed and released.

**Comment by beqramo** [comment]
@mrehan27 Hi,
please add it as I need it for Intercom. 
Currently, I'm using Onesignal and I'm getting token from them but as I'm transitioning to Customer.io I will need it from this SDK too.

Thank you!

**Comment by mrehan27** [comment]
Hey @beqramo Thanks for sharing. I have added your vote to the request internally as this will help us prioritize it. We'll let you once the feature is available.

**Comment by beqramo** [comment]
Hi @mrehan27,
any update on this?

**Comment by mrehan27** [comment]
@beqramo I apologize for the inconvenience, but we haven't started working on implementing the requested feature yet. Currently, our focus is on other high-priority items on our development roadmap. We understand the importance of this feature to you and appreciate your patience.

Please rest assured that we are actively prioritizing our development roadmap. We will keep you updated on any progress regarding the implementation of this feature.

Thank you for your understanding.

**Comment by levibostian** [comment]
This feature has been added to the React Native SDK. 

See our [docs](https://customer.io/docs/sdk/react-native/push-notifications/push/#fetch-currently-stored-device-token) to see what version of the SDK to upgrade to and how to use this new feature.
