### ISSUE TITLE
Dismiss In-App messages

### ISSUE THREAD

**Issue by scottwio** [customerio/customerio-reactnative#132]
**Is your feature request related to a problem? Please describe.**
Yes, we have a number of custom actions used on In-App Messages. These actions call functions inside our app. Some of these functions trigger navigation. Currently, we have no way to dismiss In-App Messages before the navigation happens. This results in the Application navigating behind the In-App Message; ideally, we need the In-App Message to be dismissed before the navigation happens.

**Describe the solution you'd like**
Expose a function to allow us to dismiss any currently displayed In-app message.

**Describe alternatives you've considered**
An event emitter. I did play with `CustomerIO.inAppMessaging().eventEmitter.emit('messageDismissed');` didn't get anywhere.

**Comment by Shahroz16** [comment]
Hey @scottwio, thank you for writing to us. We understand how this feature can be really handy for users. We are working on adding it and it should be available soon. Thank you for your patience.

**Comment by mrehan27** [comment]
I'm pleased to announce that we have added the feature to our SDK in version `2.4.0`. You can now dismiss the currently displayed in-app message using the following code:

```javascript
CustomerIO.inAppMessaging().dismissMessage();
```

For more information, please refer to [our documentation](https://www.customer.io/docs/sdk/react-native/in-app/#dismiss-in-app-message).

Please note that this release requires a method from the iOS SDK, which was added in version `2.6.0`. To avoid any compilation errors, please run the following command in the project's root directory:

```
pod update --repo-update --project-directory=ios
```

If you have any further questions, please don't hesitate to reach out to us.
