### ISSUE TITLE
iOS Build failure from update in the standard iOS native dependency   

### ISSUE THREAD

**Issue by EucAnt** [customerio/customerio-reactnative#146]
**SDK version:** 2.3.3

**Environment:** N/A

**Are logs available?**  N/A

**Describe the bug**
We have been getting build failures in the native iOS code with the following error:

```
❌  (node_modules/customerio-reactnative/ios/CustomerioReactnative.swift:3:8)

  1 | import Foundation
  2 | import CioTracking
> 3 | import Common
    |        ^ no such module 'Common'
  4 | import CioMessagingInApp
  5 | import UserNotifications
  6 |
```

This is related to the recent change to the naming of the common module in the iOS repo: https://github.com/customerio/customerio-ios/releases/tag/2.6.1
It doesn't seem like this has been changed in here as the imports are sill referring to the old `import Common` module name.
Yet In the pre-build logs I can see that the updated version with the new module name is getting installed with the `pod install` build step
```
...
Installing CustomerIOCommon (2.6.1)
Installing CustomerIOMessagingInApp (2.6.1)
Installing CustomerIOMessagingPush (2.6.1)
Installing CustomerIOMessagingPushAPN (2.6.1)
Installing CustomerIOTracking (2.6.1)
...
```

I can see that the [podspec](https://github.com/customerio/customerio-reactnative/blob/main/customerio-reactnative.podspec) in here is being very permissive with the version of the iOS pod that is specified:
```podspec
  s.dependency "CustomerIO/Tracking", '~> 2'
  s.dependency "CustomerIO/MessagingInApp", '~> 2'
```

I would recommend pinning the `2.6.1` pod versions and updating the imports

**To Reproduce**
- Create a project that uses this module
- Clean out the local pod cache of customerIo dependencies or run `pod upgrade` and then a `expo prebuild --clean` to pull the latest version into the cache.
- Try run an iOS build

**Expected behavior**
An app using this dependency should build.

**Screenshots** N/A

**Comment by Shahroz16** [comment]
Hey @EucAnt, thank you for reporting this. We are looking into it right now and will be sending out a fix. You are correct, it happened due to the recent iOS release.

**Comment by dsnarwariya0102** [comment]
Hello @EnuAnt , i also face this issue in the new version 2.4.1. if you run this lib need to be downgrade the version in 2.1.0 this work fine

**Comment by huyvvbka** [comment]
After updating to version 2.4.2 I got the following error. Please help me.
![Screenshot 2023-06-10 at 11 28 01](https://github.com/customerio/customerio-reactnative/assets/14915137/e27d3d51-adca-4056-a452-0d6879fed20b)

**Comment by kigh143** [comment]
Hi @huyvvbka  , did you get the solution to this issue. I am getting the same issue.
