### ISSUE TITLE
Xcode build: No such module 

### ISSUE THREAD

**Issue by wanschi** [customerio/customerio-reactnative#153]
**SDK version:** 2.4.2

**Environment:** Development 

**Are logs available?** 
During build with Xcode:

<img width="868" alt="Bildschirm­foto 2023-06-15 um 00 33 16" src="https://github.com/customerio/customerio-reactnative/assets/16665889/424aa0b2-e72a-4860-aef3-d73602397453">

**Describe the bug**
Xcode can't build the app bc of a missing cio module

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luihugo** [comment]
how did you solve this?
