### ISSUE TITLE
Xcode build: No such module 'CioInternalCommon'

### ISSUE THREAD

**Issue by wanschi** [customerio/customerio-reactnative#154]
**SDK version:** 2.4.2

**Environment:** Development 

**Are logs available?** 
During build with Xcode:

<img width="868" alt="Bildschirm­foto 2023-06-15 um 00 33 16" src="https://github.com/customerio/customerio-reactnative/assets/16665889/424aa0b2-e72a-4860-aef3-d73602397453">

**Describe the bug**
Xcode can't build the app bc of a missing cio module. 

I know that there was a fix last week (https://github.com/customerio/customerio-reactnative/pull/147) but unfortunately it throws the same error. 

**To Reproduce**
Build an app with Xcode locally

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Shahroz16** [comment]
Hey @wanschi, can you try deleting the [`derived data` ](https://www.kindacode.com/article/ways-to-delete-derived-data-in-xcode/). 

It looks like it's a cache issue.

**Comment by wanschi** [comment]
@Shahroz16 Thanks for your answer. Unfortunately that doesn't fix the problem. `expo prebuild --clean` also doesn't help.

**Comment by Shahroz16** [comment]
@wanschi are you using bare workflow? if so, can you run `pod update --repo-update` in the iOS folder?

**Comment by wanschi** [comment]
@Shahroz16 No. We're using the expo managed workflow.

**Comment by wanschi** [comment]
@Shahroz16 Thanks! If we can help you to isolate the issue please let me know. We also got some other problems with the SDK, but we first want to make sure that the issue is not on our site.

**Comment by wanschi** [comment]
@Shahroz16 Btw `pod update --repo-update ` is working local. But as we're building on EAS this won't help us.

**Comment by Shahroz16** [comment]
@wanschi thanks for clarifying, we tired to replicate and managed to not get this error in the EAS build. 

Can you please share the EAS build error stacktrace? `pod update --repo-update` should have fixed it ideally. 

We can look into EAS error stacktrace for you.

**Comment by wanschi** [comment]
@Shahroz16 Weird. This is the EAS error stracktrace: 

```
› Compiling react-native-blob-util Pods/react-native-blob-util » ReactNativeBlobUtilConst.mm
› Compiling react-native-blob-util Pods/react-native-blob-util » ReactNativeBlobUtil.mm

❌  (../../node_modules/customerio-reactnative/ios/CustomerioReactnative.swift:3:8)

  1 | import Foundation
  2 | import CioTracking
> 3 | import Common
    |        ^ no such module 'Common'
  4 | import CioMessagingInApp
  5 | import UserNotifications
  6 | 
    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'dTierarzt' from project 'dTierarzt')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'dTierarzt' from project 'dTierarzt')
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	SwiftEmitModule normal arm64 Emitting\ module\ for\ customerio_reactnative (in target 'customerio-reactnative' from project 'Pods')
▸ (1 failure)
2023-06-15 14:06:36.154 xcodebuild[5985:16359] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
** ARCHIVE FAILED **
The following build commands failed:
	SwiftEmitModule normal arm64 Emitting\ module\ for\ customerio_reactnative (in target 'customerio-reactnative' from project 'Pods')
(1 failure)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.212.2                 |
| sdk         | iPhoneOS16.4.sdk        |
+-------------+-------------------------+

```

**Comment by wanschi** [comment]
@Shahroz16 Hey, after we did `pod update --repo-update` it worked for us which is totally weird as this shouldn't affect the EAS build process. I'll close this issue. Thanks for you support!
