### ISSUE TITLE
No such module 'CioInternalCommon'

### ISSUE THREAD

**Issue by darnfish** [customerio/customerio-reactnative#162]
**SDK version:** 2.2.0

**Describe the bug**
When building an iOS app in Xcode, the following error prevents a build:
```
node_modules/customerio-reactnative/ios/CustomerioReactnative.swift:3:8 No such module 'CioInternalCommon'
```

**Additional context**
`package.json`
```
"customerio-reactnative": "^2.2.0"
```

`yarn.lock`
```
customerio-reactnative@^2.2.0:
  version "2.5.1"
  resolved "https://registry.yarnpkg.com/customerio-reactnative/-/customerio-reactnative-2.5.1.tgz#0484a970bdd8d6f2a9643eea27b039ff56e64f8e"
  integrity sha512-Y9S2RQlMwdpUdJ0OzclK5mbdh1rQGfTIrZND9ID8uu8q2Y2bHMk/hRO+ZPMp6wDnHaO7EcKQG0oUYWAyQoUYVA==
```

`Podfile.lock`
```
  - customerio-reactnative (2.5.1):
    - CustomerIO/MessagingInApp (~> 2)
    - CustomerIO/Tracking (~> 2)
    - React-Core
  - CustomerIO/MessagingInApp (2.1.2):
    - CustomerIOMessagingInApp (= 2.1.2)
  - CustomerIO/MessagingPushAPN (2.1.2):
    - CustomerIOMessagingPushAPN (= 2.1.2)
  - CustomerIO/Tracking (2.1.2):
    - CustomerIOTracking (= 2.1.2)
  - CustomerIOCommon (2.1.2)
  - CustomerIOMessagingInApp (2.1.2):
    - CustomerIOTracking (= 2.1.2)
    - Gist (~> 3.0.4)
  - CustomerIOMessagingPush (2.1.2):
    - CustomerIOTracking (= 2.1.2)
  - CustomerIOMessagingPushAPN (2.1.2):
    - CustomerIOMessagingPush (= 2.1.2)
  - CustomerIOTracking (2.1.2):
    - CustomerIOCommon (= 2.1.2)
```

**Comment by Shahroz16** [comment]
Hey @darnfish,

Thank you for writing it, can you please try this command to update the iOS pods? 

```
pod update --repo-update --project-directory=ios
```

**Comment by levibostian** [comment]
Thanks for contacting us, @darnfish

Thanks for sending us those files. It was very helpful. 

As Shahroz suggested, the native modules need to be updated to a newer version. 

There is another solution I would like to recommend, too. Our SDK just got updated to version 3.0 which will fix this issue for you and prevent it from happening again. Therefore, I recommend you upgrade to version 3 to resolve this issue. 

See our [migration doc](https://customer.io/docs/sdk/react-native/updates-and-troubleshooting/migrate-upgrade/#upgrade-from-2x-to-3x) to learn how to update (it only requires a change to your Podfile).

**Comment by darnfish** [comment]
Worked, thank you!

**Comment by ferrero1987** [comment]
@darnfish how did you solve it? I have a similar problem

**Comment by darnfish** [comment]
> @darnfish how did you solve it? I have a similar problem

I just upgraded the library to the version above :~)
