### ISSUE TITLE
No such module 'CioMessagingPush'

### ISSUE THREAD

**Issue by ferrero1987** [customerio/customerio-reactnative#189]
**customerio-reactnative:** 3.1.7
**react-native:** 0.72.4
**react:** 18.2.0
**Xcode version:** 14.3.1

MacBook Pro M1 Chip

**Describe the bug**
When building an iOS app in Xcode, the following error prevents a build:

`/Users/Documents/AwesomeProject/node_modules/customerio-reactnative/ios/CustomerioPushMessaging.swift:3:8 No such module 'CioMessagingPush'`

**Additional context**
execute command `pod update --repo-update --project-directory=ios`

**Comment by mrehan27** [comment]
Thanks for reaching out and sharing the details. We're working on a [fix](https://github.com/customerio/customerio-reactnative/pull/187) and expect to have this resolved soon. In the meantime, enabling push notifications following [instructions in documentation](https://www.customer.io/docs/sdk/react-native/push-notifications/push/) should resolve the error. If you encounter any problems or have additional questions, please don't hesitate to contact us.

**Comment by ferrero1987** [comment]
I seem to have solved it by adding to the Podfile
`pod 'customerio-reactnative/apn', :path => '../node_modules/customerio-reactnative'`

**Comment by mrehan27** [comment]
Glad to hear the issue has been resolved. Closing this now. If you have any more questions, please feel free to reach out. Thanks!
