### ISSUE TITLE
CustomerIO.getPushPermissionStatus() on android never return PushPermissionStatus.NotDetermined

### ISSUE THREAD

**Issue by AChevallier** [customerio/customerio-reactnative#190]
**SDK version:** "customerio-reactnative": "3.1.7",

**Environment:** Production

**Describe the bug**
`CustomerIO.getPushPermissionStatus()` on android never return `PushPermissionStatus.NotDetermined`  only PushPermissionStatus.Denied or PushPermissionStatus.Granted

**To Reproduce**
```
  const checkNotificationPermission = async () => {
    // logger.log('CIO will check push permission')
    const permissionResponse = await CustomerIO.getPushPermissionStatus()
    // logger.log(`CIO push permission status: ${permissionResponse}`)

    if (permissionResponse === PushPermissionStatus.NotDetermined) {
      await CustomerIO.showPromptForPushNotifications({
        ios: { sound: true, badge: true },
      })
    }
  }
```

**Expected behavior**
If this is not a bug then It should be in the documentation.
If it's a bug then it should return `PushPermissionStatus.NotDetermined` the first time we install the app, before calling `showPromptForPushNotifications`

**Comment by Shahroz16** [comment]
Hey, @AChevallier thank you for reaching out, this is just for iOS. We did try to mention it in the [docs](https://customer.io/docs/sdk/react-native/push-notifications/push/#prompt-users-for-to-opt-into-push-notifications)

>You can configure push notifications to request authorization for sounds and badges as well (only on iOS). If a user opts into push notifications, the CustomerIO.showPromptForPushNotifications method will return Granted, otherwise, it returns Denied as a string. If the user has not yet been asked to opt into notifications, the method will return NotDetermined (only for iOS).

We will definitely look into how we could have improved the copy here to be more clear.
