### ISSUE TITLE
Errors when trying to identify user on iOS

### ISSUE THREAD

**Issue by SYoder1** [customerio/customerio-reactnative#191]
**SDK version:** 3.1.8

**Are logs available?** Yes

**Describe the issue**
I am trying to setup the customer io sdk for the first time, and was able to get Android working, but on iOS when ever I call `CustomerIO.identify(userId);` the device token never shows up under the user devices. When I look into the logs I see the errors above.

**Screenshots**
<img width="1343" alt="Screenshot 2023-08-29 at 4 06 31 PM" src="https://github.com/customerio/customerio-reactnative/assets/42758479/93bc6981-5d44-4811-bcd2-6246f9afb0d1">

**Additional context**

**Comment by Shahroz16** [comment]
Hey @SYoder1, thank you for reaching out. Can you please give me details, how does the SDK initialization looks like?

**Comment by SYoder1** [comment]
Hey @Shahroz16! I actually removed all of the native code and started over, and I am still seeing them. All I did so far is a npm install and a pod install. Our minimum iOS version was already set to 14.

```
useEffect(() => {
    const env = new CustomerIOEnv();
    env.siteId = <Site ID>;
    env.apiKey = <API Key>;
    const data = new CustomerioConfig();
    data.logLevel = CioLogLevel.debug;
    data.autoTrackDeviceAttributes = true;
    data.enableInApp = true;
    CustomerIO.initialize(env, data);
  }, []);
```

**Comment by SYoder1** [comment]
Hey @Shahroz16! I actually delete the whole SDK (JS and native code) and re-added it followed the SDK installation guide to the letter. And after that it still didn't work, and I was seeing the same error.

After doing a lot more playing around, the ID I am using is from auth0, so the ID look something like `social-login|1234567890abcde`. If I remove the pipe `|` from the IDn the token get registered and uploaded and can be seen in the device tab of the user, but if I put the pipe back in, it will not upload. It looks like I can pass the email as the first parameter in the `identify()` and it will match things up correctly, but not all of our users have a email registered. Do you have any ideas?
