### ISSUE TITLE
Android is getting crashed accroding to Play store vitals

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#196]
**SDK version:**  3.1.8

**Environment:**  Production

**Are logs available?**  No

**Describe the bug**

Android Vitals are indicating that there is a crash connected to customer io:
<img width="1675" alt="image" src="https://github.com/customerio/customerio-reactnative/assets/40486471/c3362138-15f4-473f-904d-fa5a9402f867">
<img width="1090" alt="image" src="https://github.com/customerio/customerio-reactnative/assets/40486471/718a64b2-8f4c-47dd-a820-bde7e4b81b03">

And another one:
<img width="1735" alt="image" src="https://github.com/customerio/customerio-reactnative/assets/40486471/0be260df-d034-45b0-9f71-839ecf08bc04">
<img width="1406" alt="image" src="https://github.com/customerio/customerio-reactnative/assets/40486471/b600ef7a-6a52-4489-b958-00d7c1794888">

**To Reproduce**

I can't show any steps to reproduce
**Expected behavior**

shouldn't crash
**Screenshots**

**Additional context**

**Comment by Shahroz16** [comment]
Hey @beqramo thank you for reaching out, apologies for the inconvenience. We have rolled out for the second crash and can be found in the latest release ([3.1.10](https://github.com/customerio/customerio-reactnative/releases/tag/3.1.10)).

We couldn't replicate the first one but we are going to dig deeper into this.

**Comment by osamahafez** [comment]
@Shahroz16 I still get crashes in development environment on version [3.1.10](https://github.com/customerio/customerio-reactnative/releases/tag/3.1.10)

**Comment by Shahroz16** [comment]
A new [release](https://github.com/customerio/customerio-reactnative/releases/tag/3.1.11) has been rolled out which caters to these edge cases even better. Closing this issue, feel free to reopen incase you encounter this again.
