### ISSUE TITLE
Can we send iOS provisional notifications ?

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-reactnative#199]
Apple allows to send one silent notification to devices even before user agrees on receiving notifications. They call that ["provisional notifications"](https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications#3544375).
How does customer.io supports that feature ?

**Comment by ami-aman** [comment]
Hey @jbtheard 

Our React Native package does not currently support provisional notifications. However, I think this is a great feature request, so I will create a ticket internally to let the team know. 

I appreciate your queries & feedbacks.

**Comment by Shahroz16** [comment]
Closing this ticket as the feature request has been noted internally. We'll be sure to keep you updated on our progress. Thank you again for writing in.
