### ISSUE TITLE
Docs unclear on setup for RN 0.72.6

### ISSUE THREAD

**Issue by billyjacoby** [customerio/customerio-reactnative#211]
**SDK version:** 3.1.13

**Are logs available?** 
N/A
**Describe the issue**
The [docs](https://customer.io/docs/sdk/react-native/push-notifications/push/#integrate-push-capabilities-in-your-app) describe setting up in an older version of React native, specifically the `AppDelegate.h' file. The docs currently show:

```
 #import <UserNotifications/UserNotifications.h>
 @interface AppDelegate: UIResponder <UIApplicationDelegate, RCTBridgeDelegate,UNUserNotificationCenterDelegate>

 @end
```

However with a more recent version of React Native this should actually be:

```
#import <RCTAppDelegate.h>
#import <UserNotifications/UserNotifications.h>

@interface AppDelegate : RCTAppDelegate<UNUserNotificationCenterDelegate>

@end

```

**Screenshots**

**Additional context**

**Comment by levibostian** [comment]
Thank you for sending this suggestion to us. We appreciate it! 

We will have an update to our docs published shortly.
