### ISSUE TITLE
Cannot to track anonymous event

### ISSUE THREAD

**Issue by maksim-romanov** [customerio/customerio-reactnative#233]
**SDK version:**
SDK: 2.9.2, npm package: 3.3.2

**Are logs available?**
```
(siteid:cafea) ℹ️ Customer.io SDK 2.9.2 initialized and ready to use for site id: ...
(siteid:cafea) ℹ️ registering device token ...
(siteid:cafea) ℹ️ track event resend-code
(siteid:cafea) ℹ️ ignoring track event resend-code because no profile currently identified
```

**Describe the issue**
I wanna to track an anonymous event and after connect this event with real user after identify, but now i couldnt to send any events before identify user. I have also do not see this event after identify person.

**Comment by Shahroz16** [comment]
Hey @maksim-romanov, thank you for reaching out, currently `anonymous event tracking` isn't provided via SDKs. But it's in our roadmap and something we are working on.

**Comment by Shahroz16** [comment]
Hey @maksim-romanov, thank you for reaching out, unfortunately currently anonymous event tracking isn't provided via SDKs. But it's in our roadmap and something we are working on.
