### ISSUE TITLE
[Android below 13]  CustomerIO.getPushPermissionStatus() returns always granted 

### ISSUE THREAD

**Issue by fmedinaUtoppia** [customerio/customerio-reactnative#235]
**SDK version:** 
3.3.1

**Environment:** Development or Production
Both

**Describe the bug**

CustomerIO.getPushPermissionStatus() returns always granted even if its disabled in Android below 13

**To Reproduce**

Go to settings, disable push notifications permissions, log the method, returns Granted.

**Expected behavior**

Should returns Denied.

**Comment by Shahroz16** [comment]
Hey @fmedinaUtoppia, this method is just checking for `Notificatiatio Permission` which was introduced in Android 13, it doesn't check for the actual state. The permission concept for notifications was introduced in Android 13 not before that, because pre 13, notifications were always granted.
