### ISSUE TITLE
New Apple Store changes

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#248]
Hi guys,

I'm using your sdk and Apple is throwing errors as you are using some of privacy APIs.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Can you update your ios SDK accordingly?

Thanks

**Comment by felipecamposfabel** [comment]
+1 on that. Getting the API privacy message for the NotificationServiceExtension.

- NSPrivacyAccessedAPICategoryDiskSpace
- NSPrivacyAccessedAPICategoryFileTimestamp
- NSPrivacyAccessedAPICategoryUserDefaults

According to Apple?

> If you use the API in your third-party SDK’s code, then you need to report the API in your third-party SDK’s privacy manifest file. Your third-party SDK can’t rely on the privacy manifest files for apps that link the third-party SDK, or those of other third-party SDKs the app links, to report your third-party SDK’s use of required reasons API.
> For each executable or dynamic library in an app that uses a required reason API, the bundle that includes the executable or dynamic library needs to include a privacy manifest file that reports the API

**Comment by Ahmed-CIO** [comment]
Thank you both for calling this one out. It is on our radar as a priority issue to resolve. We should have it sorted out before April.

**Comment by beqramo** [comment]
@Ahmed-CIO as a suggestion: before closing this, first ticket needs to get resolved.

Also, what is the progress on this?
Thanks

**Comment by Ahmed-CIO** [comment]
@beqramo apologies for the premature closure. The task is being actively worked on during our current development cycle. Matter of validating the manifest from the relevant stakeholders to ensure we got it covered right before publishing it.

**Comment by levibostian** [comment]
This has been shipped today. 

Install the latest version of the React Native SDK, 3.6.0, in your app. Be sure to run `pod update --project-directory=ios` after you update the npm packages. 

Give it a try and let us know if you encounter problems along the way.

**Comment by felipecamposfabel** [comment]
Even tho Apple's emails are a bit inconsistent I'm still getting the warnings for:
- **ITMS-91053: Missing API declaration** - Your app’s code in the “PlugIns/NotificationServiceExtension.appex/NotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace.
- **ITMS-91053: Missing API declaration** - Your app’s code in the “PlugIns/NotificationServiceExtension.appex/NotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults.
- **ITMS-91053: Missing API declaration** - Your app’s code in the “PlugIns/NotificationServiceExtension.appex/NotificationServiceExtension” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp.

Do I need to do anything else in my notification extension other than the pod updates?

**Comment by felipecamposfabel** [comment]
I'll just leave a link about the whole Apple Privacy here, in case someone is facing any issues:

[https://github.com/react-native-community/discussions-and-proposals/discussions/776](https://github.com/react-native-community/discussions-and-proposals/discussions/776)

**Comment by levibostian** [comment]
Sorry you're facing this issue, @felipecamposfabel. 

Could you tell me more about `PlugIns/NotificationServiceExtension.appex/NotificationServiceExtension`? Could you share the code for `PlugIns/NotificationServiceExtension.appex`? It would also be valuable to see the `ios/Podfile` and `ios/Podfile.lock` files. 

The Customer.io SDK only uses `NSPrivacyAccessedAPICategoryUserDefaults` and the privacy manifest shipped with the Customer.io SDK includes this declaration. All of the other warnings are talking about APIs that the Customer.io SDK does not use. 

I am expecting to see other SDKs being used in this code that is causing these errors to show up. Answering my questions would be very helpful here. Thanks!
