### ISSUE TITLE
Linker command failed with exit code 1 (use -v to see invocation) and 2 duplicate symbols Error

### ISSUE THREAD

**Issue by teefortayyab** [customerio/customerio-reactnative#252]
**SDK version:** 3.5.3

**Are logs available?** 

**Describe the issue** 
1. Encountering "linker command failed" and "2 duplicate symbols" errors on iOS while integrating Notification Service Extension with customerio-react-native.
2. Despite following the documentation diligently, the integration process hits a roadblock with linker errors, halting the app build process.
- Steps taken include:
1. Implementing Notification Service Extension according to guidelines.
2. Ensuring adherence to customerio-react-native integration instructions.

**Screenshots**
<img width="558" alt="Screenshot 2024-04-05 at 9 40 22 PM" src="https://github.com/customerio/customerio-reactnative/assets/102040981/5e693dce-e22b-4e2e-8b6e-7b5f7312aac9">
<img width="500" alt="Screenshot 2024-04-05 at 9 43 48 PM" src="https://github.com/customerio/customerio-reactnative/assets/102040981/e28f7e1c-4765-4252-8a89-a418501ee3b7">

**Additional context**

**Comment by mrehan27** [comment]
Hi @teefortayyab, thanks for reaching out and sharing details about the issue. Sorry to hear you're encountering this issue. Have you had a chance to try the solution [suggested here](https://github.com/customerio/customerio-reactnative/issues/25#issuecomment-1277360231)? If you do and the issue persists, can you please provide the React Native version you're using, with detailed build/error logs and any other information you think might help us in reproducing the issue?

**Comment by teefortayyab** [comment]
Hey @mrehan27 ,
I already implemented that solution but still this didn't work out for me. I am using React Native **0.72.10**. and I have shared the errors above. it's the same again.
<img width="1029" alt="Screenshot 2024-04-08 at 8 31 54 PM" src="https://github.com/customerio/customerio-reactnative/assets/102040981/94e74643-65d2-4c79-a8a5-8e1c79def6cd">

**Comment by mrehan27** [comment]
Thanks for confirming @teefortayyab. Unfortunately, the details provided so far haven't helped us replicating the issue on our end. Can you please try the following and share the results with us?

1. Run [one of our sample apps](https://github.com/customerio/customerio-reactnative/tree/main/Apps) to see if you encounter any similar issues
2. Integrate our SDK into a new, empty project [following our documentation](https://customer.io/docs/sdk/react-native/) to see if it works for you. This can also help us confirm if any conflicts with other dependencies or settings are impacting your main project.

If you run into any problems or observe anything notable, please share any additional information that could help us in identifying the underlying cause.

Feel free to reach out for any questions you may have. Appreciate your patience and cooperation as we work through this together to find a solution.

**Comment by teefortayyab** [comment]
@mrehan27 Running sample project app has certain dependency issues. Is there a way we can look into it and see if the implementation is correct? With the SDK diagnostic tool, it shows everything fine. How we can further proceed?
We're currently blocked by this and we need to resolve it asap.

**Comment by mrehan27** [comment]
Thank you for sharing @teefortayyab. We understand how frustrating this can be, and we're eager to help you resolve this issue as soon as possible. However, the logs and details provided so far haven't significantly helped us in identifying the root cause.

To further assist you, please reach out to us at win@customer.io with the following information:

- A link to this ticket for reference
- Since the issue seems related to the `NotificationServiceExtenstion`, please include your `NotificationServiceExtenstion` files with any relevant details such as build settings, `Podfile`, `Podfile.lock` and deployment target
- If feasible, try removing unnecessary files/code and share a smaller version of project with us that replicates the issue. This will greatly help us in further investigation.

Please make sure any sensitive information like API keys or personal data is excluded from the files you send. If you have any more questions or need clarification on the next steps, feel free to ask.

**Comment by teefortayyab** [comment]
@mrehan27 I have emailed at win@customer.io but I haven't received any response from the team till now and still I'm blocked. Can we have plan a meeting around this so we can fix the issue? I can request for that from the customer-io's dashboard if possible but we need to settle up as we need to use customer-io for many features in the future. Let me know. Thanks

**Comment by mrehan27** [comment]
Hey @teefortayyab, we've double-checked the support requests and haven't received any request regarding this issue. Can you please confirm the email address you used is correct (i.e., win@customer.io)? If you're encountering issues with sending emails from your account, can you please ask another team member to try? Or alternatively, you can open a support request directly from the dashboard with required details by following these steps:

1. Go to Dashboard
2. Click "Need help?"
3. Click “Get help with an issue”

Thanks for your understanding. Happy to help and will continue to look into this further once we receive your request and additional information.

**Comment by teefortayyab** [comment]
I had to use Example code and Docs together to create something else to fix the issue in the project. There should be proper documentation for such features so that It doesn't confuse. The integration in Sample Apps is different than as Mentioned in the docs. Somehow I fixed it. Thanks.
