### ISSUE TITLE
Why is CustomerIOFirebaseMessagingService no longer available. 

### ISSUE THREAD

**Issue by ziga-hvalec** [customerio/customerio-reactnative#255]
I'm using the latest version of this package 3.5.4.

I'm trying to do the same as reported here https://github.com/customerio/customerio-reactnative/issues/111

We have 3 different services that all need to handle push notifications.

How do i do this since the CustomerIOFirebaseMessagingService is no longer available like in the above issue?

**Comment by levibostian** [comment]
Hello, hope you're doing well. Thanks for the details you provided thus far. 

Does [this section of our docs](https://customer.io/docs/sdk/android/push/#set-up-push) help you with this? Specifically the codeblock demonstrating how to create your own `FirebaseMessagingService` that forwards the request to the Customer.io SDK? 

Here is a screenshot highlighting the section of the docs I am talking about: 

![CleanShot 2024-04-10 at 10 12 04@2x](https://github.com/customerio/customerio-reactnative/assets/2041082/65ec1252-f119-4e32-b03f-863f09aa24cb)

If this does not help you, could you provide some code to us describing what you're trying to accomplish and what behavior you're seeing? Perhaps your `FirebaseMessagingService` subclass?

**Comment by ziga-hvalec** [comment]
this is useful. thank you. i'll let you know if i still need help
