### ISSUE TITLE
Android small notification icon

### ISSUE THREAD

**Issue by geobako** [customerio/customerio-reactnative#26]
Is there a way to set which android small icon to use when a remote notification arrives?

<img width="441" alt="Screenshot 2022-09-15 at 2 01 59 PM" src="https://user-images.githubusercontent.com/15925695/190387718-fb6702c3-e044-4ee7-8675-c2e0b93e8a17.png">

**Comment by Shahroz16** [comment]
Hey @geobako, thank you for reaching out, we currently support this only in native SDK and not the react-native one, but it's on the road-map and will be available in the next release.

**Comment by geobako** [comment]
That's great. Thanks for the quick response

**Comment by mrehan27** [comment]
Hi @geobako, starting from `1.0.0-beta.3`, you can modify the small icon by following [FCM](https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest) recommendations for Android.

### Sample Usage

```
<!-- Set custom default icon. This is used when no icon is set for incoming notification messages -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_stat_ic_notification" />

<!-- Set color used with incoming notification messages.
     This is used when no color is set for the incoming notification message -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_color"
    android:resource="@color/colorAccent" />
```
