### ISSUE TITLE
After Installing the package, I  can't pod install or gradlew build.

### ISSUE THREAD

**Issue by tdammy92** [customerio/customerio-reactnative#268]
After installing the package i get build issues on both platforms, Android and IOS .  i un-installed the package and everything was fine. 

**SDK version:** 
### SDK version 
 "customerio-reactnative": "^3.7.0",
 React-native verion
 "react-native": "0.69.7",

**Are logs available?** 

#### IOS:
```
error Failed to build the app: No package name found. Found errors in /MyMac/Desktop/Dev/SimpuMobile/node_modules/customerio-reactnative/android/src/main/AndroidManifest.xml.

[!] Invalid `Podfile` file: 859: unexpected token at 'info Run CLI with --verbose flag for more details.
'.

 #  from /Users/MyMac/Desktop/Dev/SimpuMobile/ios/Podfile:32
 #  -------------------------------------------
 #  target 'SimpuMobile' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

#### Android: 

```
 What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Users/simpuinc/Desktop/Dev/SimpuMobile/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.
```

**Describe the issue**

After installing the package i get build issues on both platforms, Android and IOS .  running  pod install or ./gradlew clean runs into errors, but when i remove the package everything will work perfectly.  

**Screenshots**

**Additional context**

**Comment by Shahroz16** [comment]
Hey @tdammy92, thank you for reaching out, apologies you are facing this. Did you update the android SDK to gradle 8, if not then please try the [version](https://github.com/customerio/customerio-reactnative/releases/tag/3.6.0) prior to it and let us know if you are still facing any issues.

**Comment by DmitryBledniuc** [comment]
I have the same issue after updating to 3.7.0 version. 3.3.2 worked perfectly. @tdammy92 did you fix the issue?

**Comment by tdammy92** [comment]
@DmitryBledniuc the new version did not work for me but i was able to use the version before that 3.6.0

**Comment by Ahmed-Ali** [comment]
@DmitryBledniuc I am closing this one since there was not much updates for a while. But please re-open if this still not working for you

**Comment by DmitryBledniuc** [comment]
@tdammy92 The same way works for me

**Comment by tdammy92** [comment]
@Ahmed-Ali its not enough to close the issue, can you point exactly what the issue is, why we could not use the new version.
so we can know what to do at our end if there is need to use the latest version.

**Comment by Shahroz16** [comment]
@tdammy92 the latest version supports Android Gradle 8 support, have you migrated your Android app to be compatible with Gradle 8?

react-native `v0.73.0` has a breaking change for Android due to AGP

[Android] Bump to AGP 8.0 https://github.com/react-native-community/discussions-and-proposals/issues/
breaking changes for libraries -> https://developer.android.com/build/releases/gradle-plugin#namespace-dsl
https://github.com/facebook/react-native/pull/37019
example: https://github.com/expo/expo/pull/22609/files#diff-ef1f15fe3a85e91b5b14cecbe065dd88e055f86f9b54c66fbdfd2c40ce95aa4b
see: https://github.com/reactwg/react-native-releases/discussions/64 for more info.

So once you bump your version to `0.73.0`, you should also utilize the latest version of SDK.

**Comment by tdammy92** [comment]
> @tdammy92 the latest version supports Android Gradle 8 support, have you migrated your Android app to be compatible with Gradle 8?
> 
> react-native `v0.73.0` has a breaking change for Android due to AGP
> 
> [Android] Bump to AGP 8.0 https://github.com/react-native-community/discussions-and-proposals/issues/ breaking changes for libraries -> https://developer.android.com/build/releases/gradle-plugin#namespace-dsl [facebook/react-native#37019](https://github.com/facebook/react-native/pull/37019) example: https://github.com/expo/expo/pull/22609/files#diff-ef1f15fe3a85e91b5b14cecbe065dd88e055f86f9b54c66fbdfd2c40ce95aa4b see: [reactwg/react-native-releases#64](https://github.com/reactwg/react-native-releases/discussions/64) for more info.
> 
> So once you bump your version to `0.73.0`, you should also utilize the latest version of SDK.

@Shahroz16 Thank you for the response, will try the new version when i bump up my React-native version.
