### ISSUE TITLE
How to connect Firebase Cloud Messaging API (V1)?

### ISSUE THREAD

**Issue by andrey-shostik** [customerio/customerio-reactnative#270]
I would like to connect push notifications with firebase in my customer io account but it requires a server key (.json) which is related to legacy API.
Is it possible to connect API v1?

![image](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/06fd0ce6-675b-4d75-ae7e-c0cae96a75cb/23cad81b-be7d-4f2c-b46c-b5a13c3ef446?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy8wNmZkMGNlNi02NzViLTRkNzUtYWU3ZS1jMGNhZTk2YTc1Y2IvMjNjYWQ4MWItYmU3ZC00ZjJjLWI0NmMtYjVhMTNjM2VmNDQ2IiwiaWF0IjoxNzE4MDQ3OTAyLCJleHAiOjMzMjg4NjA3OTAyfQ.dwD2WKJYIHoaN6DRWb6Az-urUPWqoNErUvBDJDObF_w "=1217x")

![image](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/25bd1d94-f87b-46b6-b832-dd0a8384a8b2/37d695f3-9b4d-42a3-9b0a-4a0d0864e034?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy8yNWJkMWQ5NC1mODdiLTQ2YjYtYjgzMi1kZDBhODM4NGE4YjIvMzdkNjk1ZjMtOWI0ZC00MmEzLTliMGEtNGEwZDA4NjRlMDM0IiwiaWF0IjoxNzE4MDQ3OTAyLCJleHAiOjMzMjg4NjA3OTAyfQ.SAeKqf6lA7DIUcV4EPoD1YVv0fW1wNcOQjPJwHal9bk "=1306x")

**Comment by levibostian** [comment]
Thank you for reaching out. I'd be happy to assist you with setting up FCM in the Customer.io workspace settings.

Please refer to our documentation on [setting up FCM in the Customer.io workspace settings](https://customer.io/docs/journeys/push-developer-guide/#fcm-setup). Could you let me know which step in these docs you are currently stuck on?

Additionally, I want to clarify that Customer.io does not use the FCM legacy API. Could you please specify which step in the setup process led you to believe that the legacy API is being used?

Looking forward to your response so we can resolve this issue together.

**Comment by andrey-shostik** [comment]
Thanks this doc helped me to setup the server key [setting up FCM in the Customer.io workspace settings](https://customer.io/docs/journeys/push-developer-guide/#fcm-setup).
