### ISSUE TITLE
In-app messages not working on iOS

### ISSUE THREAD

**Issue by Vepsur** [customerio/customerio-reactnative#276]
**SDK version:** 3.7.1

**Environment:** Development

**Are logs available?** 
```
error	12:25:18.034562+0400	MyApp	(siteid:cafea) 🛑 error with in-app message. id: , queueId: none, deliveryId: none
error	12:25:39.414797+0400	MyApp	(siteid:cafea) 🛑 error with in-app message. id: example-welcome, queueId: ae198e1c-9ca6-48c9-bda7-2760577a2164, deliveryId: dgSg-AcBBtoB2QEBkDTAG_BCrkesrQcYmNAx
error	12:27:44.648741+0400	MyApp	(siteid:cafea) 🛑 error with in-app message. id: , queueId: none, deliveryId: none
```

**Describe the bug**
I tried to enable the in-app messages feature.
It works on Android, but it doesn't work on iOS. In logs, I see an error about in-app messages (but it's not informational)

**To Reproduce**
-

**Expected behavior**
In-app messages work on iOS

**Screenshots**
-

**Additional context**
Push notifications and rich push notifications already work on both platforms.
I suggest it can be caused by upgrading the SDK version from 3.3.2 to 3.7.1. I didn't enable in-app messages feature on the previous version, so I can't be sure
I checked the instructions a few times, but they are not helping me.

P.S. I changed the app name in the logs if it is important

**Comment by Shahroz16** [comment]
Hey @Vepsur, thank you for reaching out, apologies that you are facing this. To help you further on this, we would need more logs to debug this further, can you enable debugging in the SDK initialization and send the logs that you captured to [win@customer.io](mailto:win@customer.io).

Thanks for your patience and support.

**Comment by Vepsur** [comment]
Thank you. I sent logs to support

**Comment by Shahroz16** [comment]
Just a heads-up, closing this as the conversation is going on Zendesk.
