### ISSUE TITLE
Android implementation not working because of gist library

### ISSUE THREAD

**Issue by santipt** [customerio/customerio-reactnative#32]
I installed the SDK for React Native on iOS and on Android. On iOS worked as expected but for Android I cannot build the project because it's throwing this error:
```
Could not determine the dependencies of task ':app:mergeBetaDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:betaDebugRuntimeClasspath'.
   > Could not find any matches for build:gist:2.1.+ as no versions of build:gist are available.
     Searched in the following locations:
       - file:/Users/user/myApp/app-mobile/node_modules/react-native/android/build/gist/maven-metadata.xml
       - file:/Users/user/myApp/app-mobile/node_modules/jsc-android/dist/build/gist/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/build/gist/maven-metadata.xml
       - https://jcenter.bintray.com/build/gist/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/build/gist/maven-metadata.xml
       - https://www.jitpack.io/build/gist/maven-metadata.xml
       - https://developer.huawei.com/repo/build/gist/maven-metadata.xml
     Required by:
         project :app > project :gistproduct_react-native
   > Could not find build:gist:2.1.4.
     Searched in the following locations:
       - file:/Users/user/myApp/app-mobile/node_modules/react-native/android/build/gist/2.1.4/gist-2.1.4.pom
       - file:/Users/user/myApp/app-mobile/node_modules/jsc-android/dist/build/gist/2.1.4/gist-2.1.4.pom
       - https://repo.maven.apache.org/maven2/build/gist/2.1.4/gist-2.1.4.pom
       - https://jcenter.bintray.com/build/gist/2.1.4/gist-2.1.4.pom
       - https://dl.google.com/dl/android/maven2/build/gist/2.1.4/gist-2.1.4.pom
       - https://www.jitpack.io/build/gist/2.1.4/gist-2.1.4.pom
       - https://developer.huawei.com/repo/build/gist/2.1.4/gist-2.1.4.pom
     Required by:
         project :app > project :customerio-reactnative > io.customer.android:messaging-in-app:3.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
Note:
I added the in-app dependency to the dependencyResolutionManagement block in my android/settings.gradle not in android/build.gradle

**Comment by mrehan27** [comment]
Hi @santipt. Looks like gradle files are unable to find the required repositories. Since you mentioned you added the in-app dependency to `android/settings.gradle`, can you please share the code you added to it?

Also, please note that `dependencyResolutionManagement` was introduced from gradle 6.8. So if you are using an older version or if your project is using the older way of setting up repositories, you might need to add the repository to `android/build.gradle` as mentioned in **2 -> [Android] -> b -> [build.gradle]** [here](https://www.customer.io/docs/sdk/react-native/getting-started/#install)

**Comment by santipt** [comment]
Hi @mrehan27 thanks for the quick reply. Here is the code I added in the `android/settings.gradle`:
```
dependencyResolutionManagement {
   repositories {
      maven { url 'https://maven.gist.build' }
   }
}
```
When I saw that adding the dependency on `android/settings.gradle` wasn't working I tried to add it on `android/build.gradle` but then I had another error: `Records requires ASM8`.

**Comment by mrehan27** [comment]
Thanks for updating @santipt. `Records requires ASM8` could be coming from moshi. Can you please add the repository back to `android/build.gradle` instead of `android/settings.gradle` and try adding the following to your `android/gradle.properties`?
```
android.jetifier.ignorelist=moshi-1.13.0
```
You can find more details on this issue [here](https://github.com/square/moshi/issues/1463#issuecomment-994576201)

**Comment by santipt** [comment]
@mrehan27 I tried to add back the repository to `android/build.gradle` and also to add `android.jetifier.ignorelist=moshi-1.13.0
`  in my `android/gradle.properties` before and it didn't work. However, I just tried again to double check and I'm having the same error: `Records requires ASM8`. 
Also to add some extra info. This is my current Gradle Version:
![Screenshot 2022-10-13 at 16 30 39](https://user-images.githubusercontent.com/36045605/195625249-5a66d6d3-d44e-4d3a-92dc-120f7ed4b129.png)

**Comment by mrehan27** [comment]
@santipt Sorry to hear that. Can you please share complete stack-trace of build errors when running the build after adding the repository to `android/build.gradle`?

**Comment by Shahroz16** [comment]
Hey @santipt, this is a very unusual issue, so any help that you can provide here would help us to debug this case even faster. 

Here is the [link](https://github.com/customerio/amiapp-reactnative/blob/main/android/build.gradle#L54) to our sample application for react, which you can probably go through and match implementation. 

Also, `Records requires ASM8` relates to `jetifier`, which is only needed when you have not done the AndroidX migration, so is it possible that you are using another dependency/library, which is not migrated to AndroidX? 

Last but not least, if nothing works, can you try adding Moshi dependency in your app separately? and exclude our ReactNative SDK? just want to confirm if Moshi conflicts with your App or any other dependency.

**Comment by santipt** [comment]
Hi @mrehan27  I just sent the email with the stack-trace of build errors to [win@customer.io](mailto:win@customer.io). @Shahroz16 let me check your suggestions to see what I can do there and then I'll come back to you  :eyes:

**Comment by santipt** [comment]
@Shahroz16 I checked and we are using another library that seems that is not migrated to AndroidX. Also I added the moshi dependency and excluded yours. I realised if I add the moshi dependency version 1.8.0 I don't see the error about `Records requires ASM8` however if I use moshi 1.13.0 it shows up again. Maybe that could help you.

**Comment by Shahroz16** [comment]
@santipt thanks for all the help. If possible can you try one more thing. Update the Gradle plugin version to 7.2 or 7.2+?

We can also probably create another version with Moshi updated but don't want to rush it out without making sure it doesn't break anything else.

**Comment by santipt** [comment]
Hey @Shahroz16 updating the Gradle plugin version to 7.2.2 worked!  :tada: I run a debug build and my app is running without errors. Thanks a lot for the help :blush:

**Comment by Shahroz16** [comment]
woot woot !! thanks for confirming @santipt. 
Closing this issue, feel free to reopen it if this arises again. 🕺
