### ISSUE TITLE
Anonymous tracking

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-reactnative#333]
**Is your feature request related to a problem? Please describe.**
Since Android and iOS now support anonymous tracking, I wonder if it's already supported on react native and expo ?

**Describe the solution you'd like**
works exactly as on Android/iOS

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Shahroz16** [comment]
Hey @jbtheard, thank you for reaching out. We are actively working on anonymous tracking support on react native and plan to ship it soon. I'll keep you updated.

**Comment by scotttwittrockcio** [comment]
We are closing this feature request ticket as we are tracking it internally. Please feel free to comment if you are also interested in this feature.

**Comment by scotttwittrockcio** [comment]
Our [React Native SDK](https://docs.customer.io/sdk/react-native/whats-new/changelog/#400) now supports Anonymous tracking! We are still working on updating the Expo Plugin to include this support.
