### ISSUE TITLE
Crash on React Native 0.76.1

### ISSUE THREAD

**Issue by dickfickling** [customerio/customerio-reactnative#351]
**SDK version:** 
I have tried 4.0.2 and 3.9.1

**Environment:** Development or Production
Development and production

**Are logs available?** 

No logs available - app crashes when importing customer.io

**Describe the bug**

Since updating to React Native 0.76.1 and enabling the new architecture, initializing customer.io causes my app to crash.

**To Reproduce**
Install React Native 0.76.1 and customer.io, then call `CustomerIO.init()`. App crashes hard with a c++ error.

**Expected behavior**
not crash

**Comment by dmitry-blackwave** [comment]
I created PR which should resolve this issue https://github.com/customerio/customerio-reactnative/pull/352. You can try https://github.com/dmitry-blackwave/customerio-reactnative/tree/fix/remove-external-parameter-label-pushmessaging and it might fix crash

**Comment by dickfickling** [comment]
That seemed to fix it. Nice sleuthing!

**Comment by ami-aman** [comment]
Hey @dickfickling,

Thank you for bringing this issue to our attention. I want to let you know that our team is actively working on this internally.

@dmitry-blackwave 
We appreciate the efforts you've put into addressing the issue. The PR you submitted is currently under review. We’ll keep this thread updated as we progress.

Thank you again for your contribution, and for helping us improve our SDK!

**Comment by mrehan27** [comment]
Changes are available in version [`4.1.1`](https://github.com/customerio/customerio-reactnative/releases). Please try it out and let us know if you have any feedback.

**Comment by leemhenson** [comment]
Is there anything that can be done here for Expo users who are locked to version 3.9 by https://github.com/customerio/customerio-expo-plugin ? Or is an Expo 52-compatible version of `customerio-expo-plugin`  arriving imminently?

**Comment by mrehan27** [comment]
Thank you for bringing this up @leemhenson. Unfortunately, support for `v4` of our React Native SDK is not yet available in our Expo plugin. However, I can confirm that it's a priority, and we are actively working on it. Unfortunately, I can't provide an exact timeline just yet, but it will be available soon. Stay tuned!

For Expo 52 support with `v3` of React Native SDK, we had to pause and aren't actively working on it at the moment, but I'll discuss this internally to prioritize and try to roll out the fix sooner after testing. Please keep an eye on https://github.com/customerio/customerio-expo-plugin/issues/155, we'll share updates on it as soon as there's some progress.

Appreciate your patience and understanding. Have a great day!
