### ISSUE TITLE
4.0.2 breaks EAS build

### ISSUE THREAD

**Issue by giaset** [customerio/customerio-reactnative#353]
**SDK version:** 4.0.2

**Environment:** Production

**Are logs available?** 

```
[!] Error installing JSONSafeEncoding
[!] /usr/bin/git -C /var/folders/vn/nzbsghpn733f46w61_gbp33r0000gn/T/d20241030-4411-qgco8o rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git
[!] [Codegen] warn: using experimental new codegen integration
[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `5867B629E93742A888FF86C4` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
Error: Unknown error. See logs of the Install pods build phase for more information.
```

**Describe the bug**
Can't build the app through EAS build when using `"customerio-reactnative": "^4.0.2"` (see pod error above). Downgrading to `"customerio-reactnative": "^3.9.1"` fixes it.

**To Reproduce**
Upgrade to 4.0.2., try to build your app on EAS

**Expected behavior**
My app to build

**Comment by ami-aman** [comment]
Hi @giaset 

Currently, our Expo plugin does not support `customerio-reactnative` version 4.0.1. You can find further details about this in our [documentation](https://docs.customer.io/sdk/expo/getting-started/#install).

This version of `customerio-reactnative` supports Customer.io Data Pipelines (CDP) and we’re actively working on bringing CDP support to Expo, though we don’t have a set timeline to share at the moment. We’ll make sure to notify you once CDP support becomes available in the Expo plugin. For now, we recommend continuing with `customerio-reactnative` version 3.9.1 or earlier.

I’ll go ahead and close this issue for now, but please feel free to reopen or add a comment if you have further questions.
