### ISSUE TITLE
Bug Report: iOS Build Failure with CioTracking Module

### ISSUE THREAD

**Issue by Valentin-Gaudin** [customerio/customerio-reactnative#366]
# Bug Report: iOS Build Failure with CioTracking Module

**SDK version:** `4.1.1`

**Environment:** Development (Monorepo with Yarn Workspaces under Expo 52)

**Are logs available?**  

**Describe the bug**  
During a local build process for an iOS app using Expo and EAS, the build fails with the following error:  
```
Error: The "Run fastlane" step failed because of an error in the Xcode build process. We automatically detected following errors in your Xcode build logs:
- no such module 'CioTracking'
```

The issue seems related to the `CioTracking` module not being found during the Xcode build process.

**To Reproduce**  
1. Run the command:
   ```bash
   eas build -p ios --local --clear-cache
   ```
2. Wait for the build process to complete.

**Expected behavior**  
The build process should complete successfully without errors, and the `CioTracking` module should be properly integrated into the iOS app.

**Screenshots**  

**Additional context**  
- The `CioTracking` module is part of the Customer.io SDK used in the app.  
- The build environment includes Expo 52, EAS, and a monorepo structure managed with Yarn Workspaces.  
The project are living in this way :
``` 
├ ROOT FOLDER
├── common
│   ├── node_modules
│   └── package.json
├── native
│   ├── node_modules
│   |   ├── customerio-expo-plugin
│   |   ├── customerio-reactnative
│   |   ├── react
│   |   └── react-native
│   └── package.json
├── node_modules
├── package.json
├── web
│   ├── node_modules
│   └── package.json
└── yarn.lock
```
- Steps like clearing the cache (`--clear-cache`) and ensuring dependencies are correctly installed have already been attempted.

**Comment by mahmoud-elmorabea** [comment]
For anyone stumbling into this issue, please refer to [this reply](https://github.com/customerio/customerio-expo-plugin/issues/185#issuecomment-2553543216)
