### ISSUE TITLE
Getting an error in (IOS + FCM) Push notification setup

### ISSUE THREAD

**Issue by Rushikesh21-12** [customerio/customerio-reactnative#48]
**SDK version:** "customerio-reactnative": "^1.0.1-alpha.1",

**Are logs available?** 
No

**Describe the issue**
Followed this documentation step by step for IOS (https://www.customer.io/docs/sdk/react-native/push/#register-push). And then getting an error at the build time.

**Screenshots**
![Error Screenshot from xcode](https://user-images.githubusercontent.com/79536918/202089462-c7e535b7-01aa-437b-9ca3-1dbe8ab32f97.png)

**Additional context**
**### Here is my Podile code**

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'Assignment2' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'CustomerIO/MessagingPushFCM', '~> 1.2.0'
  pod 'FirebaseMessaging', :modular_headers => true

  target 'Assignment2Tests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

**### Here is the Swift file code :**

`
import Foundation
import CioMessagingPushFCM
import UserNotifications

@objc
public class MyAppPushNotificationsHandler : NSObject {

  public override init() {}

  @objc(registerPushNotification:)
  public func registerPushNotification(withNotificationDelegate notificationDelegate: UNUserNotificationCenterDelegate) {

    let center  = UNUserNotificationCenter.current()
    center.delegate = notificationDelegate
    center.requestAuthorization(options: [.sound, .alert, .badge]) { (granted, error) in
      if error == nil{
        DispatchQueue.main.async {
          UIApplication.shared.registerForRemoteNotifications()
        }
      }
    }
  }

  @objc(application:deviceToken:)
  public func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    MessagingPush.shared.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
  }

  @objc(application:error:)
  public func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    MessagingPush.shared.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
  }

  @objc(userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:)
  public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
    let handled = MessagingPush.shared.userNotificationCenter(center, didReceive: response,
  withCompletionHandler: completionHandler)

    // If the Customer.io SDK does not handle the push, it's up to you to handle it and call the
    // completion handler. If the SDK did handle it, it called the completion handler for you.
    if !handled {
      completionHandler()
    }
  }
}
`

**### And lastly here is my Appdelegate.m code**
`
#import "AppDelegate.h"
#import <React/RCTLinkingManager.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
#import "Assignment2-Swift.h"

MyAppPushNotificationsHandler* pnHandlerObj = [[MyAppPushNotificationsHandler alloc] init];

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Assignment2"
                                            initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [pnHandlerObj registerPushNotification:self];
  return YES;
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [pnHandlerObj application:application deviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  [pnHandlerObj application:application error:error];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler
{
  [pnHandlerObj userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter* )center willPresentNotification:(UNNotification* )notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler( UNNotificationPresentationOptionAlert + UNNotificationPresentationOptionSound);
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

@end
`

**Comment by ami-aman** [comment]
Hi @Rushikesh21-12 
Apologies that you are getting this error, we are working on enhancing our docs and are adding FCM specific instructions as we talk.

Thanks for sharing the screenshot. Here is the solution to the issue you shared :

1. Add the following code in **MyAppPushNotificationsHandler.swift** file
```
import Foundation
import CioMessagingPushFCM

@objc
public class PushNotificationsHandler : NSObject {
  
  public override init() {}
  
  @objc(registerPushNotification:)
  public func registerPushNotification(withNotificationDelegate notificationDelegate: UNUserNotificationCenterDelegate) {
    
    let center  = UNUserNotificationCenter.current()
    center.delegate = notificationDelegate
    center.requestAuthorization(options: [.sound, .alert, .badge]) { (granted, error) in
      if error == nil{
        DispatchQueue.main.async {
          UIApplication.shared.registerForRemoteNotifications()
        }
      }
    }
  }
  
  @objc(didReceiveRegistrationToken:fcmToken:)
  func didReceiveRegistrationToken(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
    MessagingPush.shared.messaging(messaging, didReceiveRegistrationToken: fcmToken)
  }
}
```

2.  In AppDelegate.h file
```
**import <UserNotifications/UserNotifications.h>**
**import <FirebaseMessaging/FIRMessaging.h>**
@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate, **FIRMessagingDelegate**, **UNUserNotificationCenterDelegate**>
@end
```

3. In AppDelegate.m file, create an object of PushNotificationsHandler
```
PushNotificationsHandler* pnHandlerObj = [[PushNotificationsHandler alloc] init];
```
and then configure Firebase and also register for Push notifications
```
[FIRApp configure];
[FIRMessaging messaging].delegate = self;
[pnHandlerObj registerPushNotification:self];
```

4. Call handler function in **didReceiveRegistrationToken** method in **AppDelegate.m** file
```
- (void)messaging:(FIRMessaging *)messaging didReceiveRegistrationToken:(NSString *)fcmToken {
  [pnHandlerObj didReceiveRegistrationToken:messaging fcmToken: fcmToken];
}
```
And, a note: do not forget to add GoogleService-Info.plist in your project.

Please let me know if these instructions work for you. We are working on updating our docs with FCM-ObjC instructions.

**Comment by Rushikesh21-12** [comment]
Hey @ami-aman,

I have tried this solution but getting one small error in swift file. Here is the screenshot...

![Screen Shot 2022-11-16 at 2 55 46 PM](https://user-images.githubusercontent.com/79536918/202142269-37c134b7-6437-42f0-b107-f1914915399e.png)

**Comment by ami-aman** [comment]
Hi @Rushikesh21-12 
Gotcha. My bad ! You also need to do `import FirebaseMessaging`. I am updating my last comment as well to avoid confusion. 

Let me know if you need further help :)

**Comment by Rushikesh21-12** [comment]
@ami-aman 

I have added 'import FirebaseMessaging'. Previous error is gone, but now getting few more error is AppDelegate.h file.

![Screen Shot 2022-11-16 at 3 31 17 PM](https://user-images.githubusercontent.com/79536918/202150534-3cb4a47f-a40a-48a4-8582-4183f664daaa.png)

**### Here is my AppDelegate.h file code** 

#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>
#import <FirebaseMessaging/FIRMessaging.h>

@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate, FIRMessagingDelegate, UNUserNotificationCenterDelegate>
@end

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end

**Comment by ami-aman** [comment]
Awesome ! @Rushikesh21-12 

In AppDelegate.h file you just need to add the code that's marked in bold in the snippet below, in addition to whatever you had in this file previously.

Precisely, just the import statements and the two delegates !  

**import <UserNotifications/UserNotifications.h>
import <FirebaseMessaging/FIRMessaging.h>**

@ interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate, **FIRMessagingDelegate**, **UNUserNotificationCenterDelegate**>
@ end

**Comment by Rushikesh21-12** [comment]
@ami-aman Got the AppDelegate.h changes.

Now getting one Semantic issue...

![Screen Shot 2022-11-16 at 4 02 20 PM](https://user-images.githubusercontent.com/79536918/202157920-15fab08e-32e7-44d2-8794-56a745ddd43e.png)

**Comment by ami-aman** [comment]
@Rushikesh21-12 
That is because you are creating the object at the wrong place. It should be inside AppDelegate implementation i.e. 

@implementation AppDelegate // Inside this implementation block
// Right here 
PushNotificationsHandler* pnHandlerObj = [[PushNotificationsHandler alloc] init];

**Comment by Rushikesh21-12** [comment]
@ami-aman 

moved the code into implementation block, Still getting the same error...

![Screen Shot 2022-11-16 at 4 22 23 PM](https://user-images.githubusercontent.com/79536918/202161702-222e7ca3-4919-4dc7-975d-357fbe074d8a.png)

**Comment by ami-aman** [comment]
@Rushikesh21-12 
Did you try deleting the derived data, cleaning the build folder, restart metro bundler and re-launch the app ?

**Comment by Rushikesh21-12** [comment]
@ami-aman 

Yes i have tried all this things. But no luck.

**Comment by Rushikesh21-12** [comment]
Hey @ami-aman, 

I have tried the same setup in another project but facing the same issue : Initializer element is not a compile-time constant ([This error](https://github.com/customerio/customerio-reactnative/issues/48#issuecomment-1316800592))

**Comment by ami-aman** [comment]
Hi @Rushikesh21-12 
This is a strange error, I haven't seen it yet ! I am creating a ticket and someone from our team will investigate it internally. We'll get back to you soon!

**Comment by melissakintz** [comment]
Hi ! 
I've also get this error and successfully resolve it adding this line on AppDelegate.m:
```objc
@implementation AppDelegate
PushNotificationsHandler* pnHandlerObj = nil;

+ (void)initialize {
  pnHandlerObj = [[pnHandlerObj alloc] init];
}

```

**Comment by Rushikesh21-12** [comment]
@melissakintz it works for me.

Thank you @ami-aman and @melissakintz

**Comment by claudesortwell** [comment]
> Hi ! I've also get this error (Initializer element is not a compile- time constant) and successfully resolve it adding these lines on AppDelegate.m:
> 
> ```objc
> @implementation AppDelegate
> PushNotificationsHandler* pnHandlerObj = nil;
> 
> + (void)initialize {
>   pnHandlerObj = [[pnHandlerObj alloc] init];
> }
> ```

@ami-aman This should be added to the docs [https://customer.io/docs/sdk/react-native/push/](https://customer.io/docs/sdk/react-native/push/)
