### ISSUE TITLE
More option to Handle Notification permission

### ISSUE THREAD

**Issue by MatiasLjubica** [customerio/customerio-reactnative#58]
**Showing the notification permission at the start is to basic**

Actually on IOS the notification permission modal is showing on the start but in some case we want to show it after some event or a custom page or ask again 

**Add some function and options**

It will helpfull if we can have more interaction with it like OneSignal

```javascript
import OneSignal from 'react-native-onesignal';

// OneSignal Initialization
OneSignal.setAppId(ONESIGNAL_APP_ID);

// promptForPushNotificationsWithUserResponse will show the native iOS or Android notification permission prompt.
// We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 8)

OneSignal.promptForPushNotificationsWithUserResponse();

//Method for handling notifications received while app in foreground
OneSignal.setNotificationWillShowInForegroundHandler(notificationReceivedEvent => {
  console.log("OneSignal: notification will show in foreground:", notificationReceivedEvent);
  let notification = notificationReceivedEvent.getNotification();
  console.log("notification: ", notification);
  const data = notification.additionalData
  console.log("additionalData: ", data);
  // Complete with null means don't show a notification.
  notificationReceivedEvent.complete(notification);
});

//Method for handling notifications opened
OneSignal.setNotificationOpenedHandler(notification => {
  console.log("OneSignal: notification opened:", notification);
});
```

Thank you

**Comment by ami-aman** [comment]
Hi @MatiasLjubica 
Thank you for the feature request, I appreciate it. I am creating a FR ticket internally so that someone from our team can work on it and add this feature into our package. 

Feel free to add more points to this request, anytime !

**Comment by makan-amini** [comment]
Hi. @ami-aman is this fixed? Very big deal not to be able to control when the notification permission shows up.

**Comment by ami-aman** [comment]
Hi @makan-amini 
Our team is already working on this feature. We hope to release it soon ! I will keep you posted !

**Comment by superphil0** [comment]
Do you have a timeline @ami-aman ? We waiting for this as well

**Comment by makan-amini** [comment]
@superphil0 - We've been stalled for 3 months on Customer.io problems and new ones popped up all the time. We switched to Iterable on Feb 1 and area already up and running with no issues. Strongly recommend switching away from Customer.io asap.

**Comment by matt-frizzell** [comment]
Hello all, I'm Matt, the Director of Mobile Engineering at [Customer.io](http://customer.io/), and I want to step in here and acknowledge that the difficulties that Makan and his developer experienced when integrating this SDK weren't up to our standard.  We're continuing to improve our SDKs every day and appreciate the patience and support of the developer community through issues like this.

The good news is that not only is this issue well underway, but we are in the final stage of development, where we validate our changes to ensure a successful release. This is a top priority, and is on track to be released next week. I'm also always available at [frizzell@customer.io](mailto:frizzell@customer.io) or reach out through GitHub or our Support team and they'll be sure to connect us.

**Comment by makan-amini** [comment]
You have been in "final stage of development" since Thanksgiving.

**Comment by matt-frizzell** [comment]
Happy Friday everyone. I'm back to let you know that this functionality is [unlocked and live in the new 2.2.0 release](https://customer.io/docs/sdk/react-native/changelog/#2.2.0)! To use this, please check out that new version and follow along with the [updated documentation for setting up push notifications](https://customer.io/docs/sdk/react-native/push/).

Feel free to let us know if you have any additional feedback, but otherwise, I'll close this request out as complete.

**Comment by MatiasLjubica** [comment]
Thanks team, can this new SDK work with the Expo plugin ?

**Comment by matt-frizzell** [comment]
@MatiasLjubica Thanks for asking, as it is an excellent question. For this change our Expo plugin does need an update and those changes are up next for us.

I'll pop back in here and update you when that Expo version is up.

**Comment by xtreem88** [comment]
I have a new PR ready with the required changes

**Comment by matt-frizzell** [comment]
@MatiasLjubica You might have noticed this already, but that PR that @xtreem88 mentioned did turn into a [release of the Expo plugin](https://github.com/customerio/customerio-expo-plugin/releases/tag/1.0.0-beta.7), which we hope helps you and others out. If you've got anything else we can look at, feel free to reach out.

Have a great weekend!

**Comment by MatiasLjubica** [comment]
Thanks @xtreem88  and @matt-frizzell
