### ISSUE TITLE
Support for Rich in app messages

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#60]
Hi,
We would like to move entirely to Customer.io but one limitation we are facing is the lack of features, especially this one.
Can you tell me if you have any timeline for this feature?
Thanks

**Comment by lj-cio** [comment]
Hi @beqramo, 

We added in-app message support to Customer.io last quarter and are currently in an open beta!  If you're interested in setting this up in your account and trying it out now, you can find the setup guide for React Native [here](https://customer.io/docs/sdk/react-native/in-app/).  More information + a video overview of in-app is also available in our [general documentation](https://customer.io/docs/in-app-getting-started/).

Email product@customer.io if you have any questions or specific use cases that you want to discuss!

Cheers,
LJ

**Comment by lj-cio** [comment]
Closing this issue for now, please feel free to re-open if I haven't addressed your question.  I'll also keep an eye out in the product@customer.io inbox.

**Comment by Shahroz16** [comment]
Hey @beqramo thanks for writing in, RN SDK does [support](https://www.customer.io/docs/sdk/react-native/push/) Rich push. 

Is there any issue that you are facing?

**Comment by beqramo** [comment]
Okay thanks, just were confused as on other SDK integration it has separate tab for rich in-app messages

**Comment by beqramo** [comment]
Hi @Shahroz16 @lj-cio 
I start integrating and I see this:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/40486471/209375149-c96b2338-7557-40c1-8cf1-f8280770c218.png">
at the end of this section: https://customer.io/docs/sdk/react-native/push/#rich-push

So again, the question will be when you plan to integrate that.

**Comment by lj-cio** [comment]
Glad to hear that you're working through the integration, @beqramo, and apologies for the confusion here.  Let me try to confirm that first:

In your follow-up note above, you shared our rich push documentation, which is the same as OneSignal's push service described [here](https://documentation.onesignal.com/docs/sending-notifications#sending-push-notifications-from-dashboard) and appear outside of your app, like this: 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/53791868/209394385-18593fae-9c0e-440c-b13c-aed7d9316ab2.png">

But in the initial description for this issue, you mentioned in-app messages, which is the same as OneSignal's in-app service described [here](https://documentation.onesignal.com/docs/design-your-in-app-message).  Here's an example of a message built using CIO's in-app messaging feature (one we recently used ourselves):

<img width="200" alt="image" src="https://user-images.githubusercontent.com/53791868/209394036-fa0b9380-0a0d-4930-bfde-5da33edc85ae.png">

Both rich push and in-app messages are available today in CIO's React Native SDK, no custom code needed.  The custom code that is mentioned in the screenshot that you shared for rich push notifications is only particular to push notifications.

Let me know if this answers your question, or if I've totally misunderstood here.  If it's the latter, reach out to product@customer.io so we can dive into your specific goals and use cases and make sure we address them!
