### ISSUE TITLE
Unable to set up push notifications in IOS

### ISSUE THREAD

**Issue by lucasbeatdapp** [customerio/customerio-reactnative#65]
**SDK version:**     "customerio-reactnative": "^1.0.0"

**Environment:** Development

**Are logs available?** 
```
[!] CocoaPods could not find compatible versions for pod "CustomerIOTracking":
  In Podfile:
    CustomerIO/MessagingPushFCM (~> 2.0.1) was resolved to 2.0.1, which depends on
      CustomerIOMessagingPushFCM (= 2.0.1) was resolved to 2.0.1, which depends on
        CustomerIOMessagingPush (= 2.0.1) was resolved to 2.0.1, which depends on
          CustomerIOTracking (= 2.0.1)

    customerio-reactnative (from `../node_modules/customerio-reactnative`) was resolved to 1.0.0, which depends on
      CustomerIOTracking (~> 1.2.0)
```

**Describe the bug**

Unable to follow the steps in [this](https://customer.io/docs/sdk/react-native/push/#register-push) documentation at step which is adding `  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.1'` in my podfile.

**To Reproduce**

React: 18
react-native: 0.70.5

**Expected behavior**

Be able to run `cd ios && pod install && cd ..` without an error

**Comment by lucasbeatdapp** [comment]
Nice! That worked, was able to install the pods without an issue!

**Comment by Shahroz16** [comment]
Awesome, thanks for confirming.

**Comment by lucasbeatdapp** [comment]
Hey @Shahroz16 thank you! I'm currentyy running into a separate issue. Following the steps to add [Push Notifications](https://customer.io/docs/sdk/react-native/push/#register-push)

I am using the options FCM and Objective-C

I added the `NotificationHandler.swift` file in the root of my ios project
AND
I also made the changes in my AppDelegate.h
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <Expo/Expo.h>
#import <UserNotifications/UserNotifications.h>
#import <FirebaseMessaging/FIRMessaging.h>

@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate, UNUserNotificationCenterDelegate, FIRMessagingDelegate>

@end

```

At this point, I can build with no issue.

At step 6 and 7 I have confusion.

The top of my AppDelegate.mm loooks like this: 
```
#import <Firebase.h>
#import <FirebaseCore.h>
#import "AppDelegate.h"
```

In step 6, is `#import <MyAppProject-Swift.h>` referring to my "AppDelegate.h"? or some other file that I'm unaware of.

I can still build with my imports above

Next in step 7: 

With adding directly below my `@implementation AppDelegate`
```
NotificationHandler* pnHandlerObj = [[NotificationHandler alloc] init];
```

 I get this error:
 
 ```
/Users/lucas/myapp/ios/myapp/AppDelegate.mm:35:2: error: unknown type name 'NotificationHandler'; did you mean 'NSNotificationCenter'?
 NotificationHandler* pnHandlerObj = [[NotificationHandler alloc] init];
 ^~~~~~~~~~~~~~~~~~~
 NSNotificationCenter
In file included from /Users/lucas/myapp/ios/myapp/AppDelegate.mm:1:
In file included from /Users/lucas/Library/Developer/Xcode/DerivedData/myapp-aoxnfueqniuliffmgtuxziljixgs/Build/Products/Debug-iphonesimulator/FirebaseCore/FirebaseCore.framework/Headers/FirebaseCore.h:17:
In file included from /Users/lucas/Library/Developer/Xcode/DerivedData/myapp-aoxnfueqniuliffmgtuxziljixgs/Build/Products/Debug-iphonesimulator/FirebaseCore/FirebaseCore.framework/Headers/FIRApp.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:58:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSNotificationQueue.h:8:24: note: 'NSNotificationCenter' declared here
@class NSNotification, NSNotificationCenter, NSArray<ObjectType>, NSString;
                       ^
/Users/lucas/myapp/ios/myapp/AppDelegate.mm:35:40: error: use of undeclared identifier 'NotificationHandler'
 NotificationHandler* pnHandlerObj = [[NotificationHandler alloc] init];
```

Is this line placed in the correct location?
<img width="958" alt="Screenshot 2023-01-06 at 1 54 48 PM" src="https://user-images.githubusercontent.com/72827990/211106563-d7c5d940-068c-4745-b665-420a739787f1.png">

Any help would be incredibly appreciated!

**Comment by lucasbeatdapp** [comment]
I figured out what was meant in step 6. I have no imported this into my AppDelegate.mm
```
#import <Firebase.h>
#import "AppDelegate.h"
#import <FirebaseCore.h>
#import <ProductName-Swift.h>
```

The error I am now running into is related to have Expo modules installed on my app:

```
/Users/lucas/Library/Developer/Xcode/DerivedData/myapp-aoxnfueqniuliffmgtuxziljixgs/Build/Intermediates.noindex/myapp.build/Debug-iphonesimulator/myapp.build/DerivedSources/ProductName-Swift.h:257:34: error: cannot find interface declaration for 'ModulesProvider', superclass of 'ExpoModulesProvider'
@interface ExpoModulesProvider : ModulesProvider
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^
13 warnings and 1 error generated.
```

This looks like I'm running into an issue with having the expo modules installed and being used in my `AppDelegate.h`

**Comment by lucasbeatdapp** [comment]
Was able to build after adding `#import "ExpoModulesCore-Swift.h"` before `#import "ProductName-Swift.h"`

My imports now look like this:
```
#import <Firebase.h>
#import "AppDelegate.h"
#import <FirebaseCore.h>
#import "ExpoModulesCore-Swift.h"
#import "ProductName-Swift.h"
```

Also, I didn't realize when importing header files you need to wrap the imports in quotation marks("") instead of alligator tags (<>).

For anyone else experiencing this issue
