### ISSUE TITLE
RN package crashes at startup

### ISSUE THREAD

**Issue by dcsan** [customerio/customerio-reactnative#66]
**SDK version:** 
"customerio-reactnative": "1.0.1-alpha.1",

**Environment:** Development or Production
dev 

**Are logs available?** 

**Describe the bug**
Fatal error at startup of our app

![image](https://user-images.githubusercontent.com/514002/211014344-9dab6449-2189-417e-958a-15f768b1f294.png)

**To Reproduce**
install and init RN package

**Expected behavior**
package doesn't crash our app

**Screenshots**
above

**Additional context**
```
2023-01-06 03:53:13.242103-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 150] RNFBCrashlyticsInit crashlytics_debug_enabled via RNFBJSON: 0
2023-01-06 03:53:13.242209-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 160] RNFBCrashlyticsInit crashlytics_debug_enabled final value: 0
2023-01-06 03:53:13.242260-0800 revelapp[71145:225592] +[RNFBCrashlyticsInitProvider isCrashlyticsCollectionEnabled] [Line 49] RNFBCrashlyticsInit isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: 0
2023-01-06 03:53:13.242350-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 150] RNFBCrashlyticsInit crashlytics_is_error_generation_on_js_crash_enabled via RNFBJSON: 1
2023-01-06 03:53:13.242394-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 160] RNFBCrashlyticsInit crashlytics_is_error_generation_on_js_crash_enabled final value: 1
2023-01-06 03:53:13.242430-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 150] RNFBCrashlyticsInit crashlytics_javascript_exception_handler_chaining_enabled via RNFBJSON: 0
2023-01-06 03:53:13.242466-0800 revelapp[71145:225592] +[RNFBSharedUtils getConfigBooleanValue:key:defaultValue:] [Line 160] RNFBCrashlyticsInit crashlytics_javascript_exception_handler_chaining_enabled final value: 0
2023-01-06 03:53:13.242610-0800 revelapp[71145:225592] [native] Crashlytics - WARNING: Debugger detected. Crashlytics will not receive crash reports.
CioMessagingInApp/MessagingInApp.swift:21: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2023-01-06 03:53:13.279677-0800 revelapp[71145:223985] CioMessagingInApp/MessagingInApp.swift:21: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

crash is on this line:

`diGraphOverride ?? DIGraph.getInstance(siteId: siteId)`

```
    const data = new CustomerioConfig();
    data.logLevel = CioLogLevel.debug;
    data.autoTrackDeviceAttributes = true;
    data.autoTrackPushEvents = true;

    const env = new CustomerIOEnv();
    env.siteId = "[redact]";
    env.apiKey = "[redact]";
    env.organizationId = "[redact]";
    env.region = Region.US;

    CustomerIO.initialize(env, data);
```

When I remove that `.initialize` our app will start up succesfully.

**Comment by dcsan** [comment]
could be similar to #29 ?
is the bump from 1.0.alpha.1 to alpha.3 or even to 2.0 likely to fix this?

**Comment by levibostian** [comment]
Thank you for reporting this. We appreciate it. 

From all the helpful information you provided (thank you!), I can tell this is [the same issue reported inside of the iOS SDK](https://github.com/customerio/customerio-ios/issues/242). Our React Native SDK is a bridge/wrapper SDK around our iOS and Android SDKs so any issues that the iOS or Android SDKs have, the React Native SDK has. 

There is [a bug fix proposed](https://github.com/customerio/customerio-ios/pull/243) to the team to fix this issue. We plan to get it released to production v1 as soon as possible. 

However, we do highly recommend upgrading to version 2 of the React Native SDK. This bug is not present in version 2 of the React Native/iOS SDKs.

**Comment by levibostian** [comment]
The iOS SDK has released version 1.2.9 to production which includes a bug fix for this issue. 

We still recommend using version 2 of the SDK which does not have this bug present. However, if you would like to use version 1, update your dependencies including perform `pod update` in your iOS app to install the latest v1 of the iOS SDK into your React Native app. 

I'm going to close this issue for now. If you are still encountering issues, we can re-open it.

**Comment by dcsan** [comment]
thanks for the updates

To upgrade this - first of all just within 1.0 for this reactnative package

there is no update?
https://github.com/customerio/customerio-reactnative/releases

since we're on alpha.1 i did try simply changing the npm package version and installing, but got errors with the Pod files. 

So I somehow have to modify the native dependencies of your RN package? or just update the pods underneath - seems like a shifty thing to do.

> The iOS SDK has released version 1.2.9 

"The" ? What ios SDK was updated? Which pods?
There are a ton of your pods I see in our project:

```
  - customerio-reactnative (1.0.1-alpha.1):
    - CustomerIOMessagingInApp (~> 1.2.1)
    - CustomerIOTracking (~> 1.2.1)
    - React-Core
  - CustomerIO/MessagingPushAPN (1.2.8):
    - CustomerIOMessagingPushAPN (= 1.2.8)
  - CustomerIOCommon (1.2.8)
  - CustomerIOMessagingInApp (1.2.8):
    - CustomerIOTracking (= 1.2.8)
    - Gist (~> 2.2.1)
  - CustomerIOMessagingPush (1.2.8):
    - CustomerIOTracking (= 1.2.8)
  - CustomerIOMessagingPushAPN (1.2.8):
    - CustomerIOMessagingPush (= 1.2.8)
  - CustomerIOTracking (1.2.8):
    - CustomerIOCommon (= 1.2.8)
```

Since you perhaps know what's changed it would be helpful if you could let me know.

FWIW i did try (since it was on 1.2.8) 

`pod update CustomerIO/MessagingPushAPN`

but this changed nothing.

A few more breadcrumbs along the trail of broken packages please.

**Comment by dcsan** [comment]
OK I took a guess and updated the podfile:

`pod 'CustomerIO/MessagingPushAPN', '~> 1.2.9'` 

and the RN plugin to `.alpha.3`

`    "customerio-reactnative": "1.0.1-alpha.3", `

when I try to `pod install`  now get this incompatibility report
remove podfile.lock gives same result



```
[!] CocoaPods could not find compatible versions for pod "CustomerIOTracking":
  In Podfile:
    CustomerIO/MessagingPushAPN (~> 1.2.9) was resolved to 1.2.9, which depends on
      CustomerIOMessagingPushAPN (= 1.2.9) was resolved to 1.2.9, which depends on
        CustomerIOMessagingPush (= 1.2.9) was resolved to 1.2.9, which depends on
          CustomerIOTracking (= 1.2.9)

    customerio-reactnative (from `../node_modules/customerio-reactnative`) was resolved to 1.0.1-alpha.3, which depends on
      CustomerIOMessagingInApp (~> 2.0.0-alpha.1) was resolved to 2.0.1, which depends on
        CustomerIOTracking (= 2.0.1)

    customerio-reactnative (from `../node_modules/customerio-reactnative`) was resolved to 1.0.1-alpha.3, which depends on
      CustomerIOTracking (~> 2.0.0-alpha.1)

```

not sure if this means that the bump within 1.0 RN package from alpha.1 to alpha.3 ... somehow broke things such that it depends on a 2.0 of the native pod? that seems weird.

anyway so tried then going back to a previous alpha:

`    "customerio-reactnative": "1.0.1-alpha.1", `

and it _seems_ like I can install now. at least, it doesn't crash on install.

is the RN package  v2.0 API compatible with v1  or would we have to change code to upgrade?

**Comment by dcsan** [comment]
also now most of these are on 1.2.9 but not all?

```
  - customerio-reactnative (1.0.1-alpha.1):
    - CustomerIOMessagingInApp (~> 1.2.1)
    - CustomerIOTracking (~> 1.2.1)
    - React-Core
  - CustomerIO/MessagingPushAPN (1.2.9):
    - CustomerIOMessagingPushAPN (= 1.2.9)
  - CustomerIOCommon (1.2.9)
  - CustomerIOMessagingInApp (1.2.9):
    - CustomerIOTracking (= 1.2.9)
    - Gist (~> 2.2.1)
  - CustomerIOMessagingPush (1.2.9):
    - CustomerIOTracking (= 1.2.9)
  - CustomerIOMessagingPushAPN (1.2.9):
    - CustomerIOMessagingPush (= 1.2.9)
  - CustomerIOTracking (1.2.9):
    - CustomerIOCommon (= 1.2.9)
```

these are not updated, is that correct?

```
    - CustomerIOMessagingInApp (~> 1.2.1)
    - CustomerIOTracking (~> 1.2.1)
```

**Comment by levibostian** [comment]
Sorry for not being descriptive enough with how to perform an update to 1.2.9. 

The React Native SDK did not have any new version released. The bug did not exist inside of the Customer.io React Native SDK but the Customer.io iOS SDK that the React Native SDK uses internally. So, the bug fix was inside of the iOS SDK which is what you have been trying to update correctly on your own. Great! 

From your comments, you're doing everything correctly. You're updating all of the Customer.io dependencies inside of your `Podfile` to 1.2.9

About [your last comment](https://github.com/customerio/customerio-reactnative/issues/66#issuecomment-1374929214), 
```
  - customerio-reactnative (1.0.1-alpha.1):
    - CustomerIOMessagingInApp (~> 1.2.1) <-- seeing 1.2.1, not 1.2.9
    - CustomerIOTracking (~> 1.2.1)   <-- seeing 1.2.1, not 1.2.9
    - React-Core
  - CustomerIO/MessagingPushAPN (1.2.9):
    - CustomerIOMessagingPushAPN (= 1.2.9)
  - CustomerIOCommon (1.2.9)
  - CustomerIOMessagingInApp (1.2.9):
    - CustomerIOTracking (= 1.2.9)
    - Gist (~> 2.2.1)
  - CustomerIOMessagingPush (1.2.9):
    - CustomerIOTracking (= 1.2.9)
  - CustomerIOMessagingPushAPN (1.2.9):
    - CustomerIOMessagingPush (= 1.2.9)
  - CustomerIOTracking (1.2.9):
    - CustomerIOCommon (= 1.2.9)
```

This log message shows that you did everything correctly. 

The React Native SDK's dependencies are listed at the top:
```
  - customerio-reactnative (1.0.1-alpha.1):
    - CustomerIOMessagingInApp (~> 1.2.1)
    - CustomerIOTracking (~> 1.2.1) 
    - React-Core
```

The dependencies say that it requires the Customer.io iOS SDK *at least* version 1.2.1, but could be newer then that. It's not specifying what is actually installed - just it's requirements. 

Then, if you look farther down in your logs, you will see what version is actually installed of each of these dependencies:
```
  - CustomerIO/MessagingPushAPN (1.2.9):
  - CustomerIOCommon (1.2.9)
  - CustomerIOMessagingInApp (1.2.9):
  - CustomerIOMessagingPush (1.2.9):
  - CustomerIOMessagingPushAPN (1.2.9):
  - CustomerIOTracking (1.2.9):
```

All say 1.2.9 meaning you did everything correct!

**Comment by dcsan** [comment]
ok got it, tx for the detail. 

so it won't pull in multiple versions like some package managers.

also the [tilde vs caret](https://nodesource.com/blog/semver-tilde-and-caret/) was a bit unclear
like [resolutions](https://www.jondjones.com/frontend/javascript/npm-packages-for-javascript-developers/yarn-resolutions-to-the-rescue/)
