### ISSUE TITLE
native pods and reactnative versions conflict

### ISSUE THREAD

**Issue by dcsan** [customerio/customerio-reactnative#68]
**SDK version:** 
RN1. x 

**Environment:** Development or Production
both

**Are logs available?** 
see below

**Describe the bug**
related to this:  https://github.com/customerio/customerio-reactnative/issues/66#issuecomment-1373937688
> The iOS SDK has released version 1.2.9 to production which includes a bug fix for this issue.

BUT your RN modules still refer to the old crashing version
Trying to update the reactnative package to get around some issues, 
I noticed oddness in the underlying pods used

1.0 alpha 1 => rn 1.2.1
  s.dependency "React-Core"
  s.dependency "CustomerIOTracking", '~> 1.2.1'
  s.dependency "CustomerIOMessagingInApp", '~> 1.2.1'

see here https://github.com/customerio/customerio-reactnative/blob/1.0.1-alpha.1/customerio-reactnative.podspec

1.0 alpha 3 => rn 2.0
https://github.com/customerio/customerio-reactnative/blob/1.0.1-alpha.3/customerio-reactnative.podspec

  s.dependency "React-Core"
  s.dependency "CustomerIOTracking", '~> 2.0.0-alpha.1'
  s.dependency "CustomerIOMessagingInApp", '~> 2.0.0-alpha.1'

So, how do I fix this? Should I fork your repo and update these?

When I did a manual install I get two versions of your IOS package in my Podfile.lock:

```
  - customerio-reactnative (1.0.1-alpha.1):
    - CustomerIOMessagingInApp (~> 1.2.1)    <==== created by your outdated dependency
    - CustomerIOTracking (~> 1.2.1) 
    - React-Core
  - CustomerIO/MessagingPushAPN (1.2.9):
    - CustomerIOMessagingPushAPN (= 1.2.9)
  - CustomerIOCommon (1.2.9)
  - CustomerIOMessagingInApp (1.2.9):     <==== as part of our podfile install
    - CustomerIOTracking (= 1.2.9)
    - Gist (~> 2.2.1)
  - CustomerIOMessagingPush (1.2.9):
    - CustomerIOTracking (= 1.2.9)
  - CustomerIOMessagingPushAPN (1.2.9):
    - CustomerIOMessagingPush (= 1.2.9)
  - CustomerIOTracking (1.2.9):
    - CustomerIOCommon (= 1.2.9)
    - 
```

So is it OK to use the 2.0 ios SDK with the 1.0 version of the react-native package? This seems odd.

also if the RN package is now updated to 2.0, is this compatible with the 1.0?

--- how best to install / update and linking updated IOS module?

we're on 
> "react-native": "0.69.7",

So I don't think this:

`npx react-native link customerio-reactnative`

 is needed anymore, 

We do have a Podfile in the repo where I have to manually update references. 
I inherited this part of the project so not sure where these came from maybe it was prior to RN60?
This is what is installing the incompatible versions.

```ruby
    target 'dev-XXXXapp' do
      use_expo_modules!
      config = use_native_modules!

      use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

      # Flags change depending on the env values.
      flags = get_default_flags()

      permissions_path = '../node_modules/react-native-permissions/ios'

      pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
      pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
      pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
      # DC updated see https://github.com/customerio/customerio-reactnative/issues/66
      pod 'CustomerIO/MessagingPushAPN', '~> 1.2.9'
```

**Comment by levibostian** [comment]
Thanks for making a ticket about this. 

I sent a response [here](https://github.com/customerio/customerio-reactnative/issues/66#issuecomment-1375764025) in this other issue that should answer your question. 

I'll close this issue for now assuming it answers your question. Comment back if it doesn't.
