### ISSUE TITLE
push_enabled set to false when registering a device on ios

### ISSUE THREAD

**Issue by alon7** [customerio/customerio-reactnative#76]
**SDK version:** 2.0.0

**Environment:** Development and Production

**Are logs available?** 

```
[CIO] (siteid:<siteId>) ℹ️  registering device token <redacted_device_token>
[CIO] (siteid:<siteId>) ℹ️ no profile identified, so not registering device token to a profile
[CIO] (siteid:<siteId>) ℹ️ registering device token <redacted_device_token>
[CIO] (siteid:<siteId>) storing device token to device storage <redacted_device_token>
[CIO] (siteid:<siteId>) ℹ️ no profile identified, so not registering device token to a profile
[CIO] (siteid:<siteId>) registering existing device token to newly identified profile: <profile_identifier>
[CIO] (siteid:<siteId>) ℹ️ registering device token <redacted_device_token>
[CIO] (siteid:<siteId>) storing device token to device storage <>
[CIO] (siteid:<siteId>) ℹ️ adding queue task registerPushToken
registerPushToken, {"attributes_json_string":"{\"device\":{\"attributes\":{\"app_version\":\"x.x.x\",\"cio_sdk_version\":\"2.0.0\",\"device_locale\":\"en-US\",\"device_manufacturer\":\"Apple\",\"device_model\":\"iPhone15,3\",\"device_os\":\"16.1.1\",\"push_enabled\":\"false\"},\"id\":\"<id>\",\"last_used\":<time>,\"platform\":\"iOS\"}}","profile_identifier":"<profile_identifier>"}, QueueTaskRunResults(totalRuns: 0)
```

**Describe the bug**
In our app, we don't want to request push notification permissions as soon as the app launches, so we are not calling the `registerPushNotification` method on app startup. 

We ask for the permissions later, and then we see the logs above where the device token is being sent to customer.io, but for some reason, `push_enabled` is set to `false`. If we ask for permissions when the app launches, `push_enabled` is set to `true`. 

We use FCM to send push for both ios and android. 

**To Reproduce**
add the following to appdelegate:
```
    pnHandlerObj = [[MyAppPushNotificationsHandler alloc] init];
    [FIRMessaging messaging].delegate = self;
    [pnHandlerObj initializeCioSdk];
```

don't call `registerPushNotification` and ask for the user permission later in the flow

**Expected behavior**
Set the `push_enabled` flag to true, so we can send and interact with the user.

**Screenshots**
<img width="517" alt="Screen Shot 2023-01-30 at 17 46 00" src="https://user-images.githubusercontent.com/176762/215524319-78989f03-bd89-46dd-a18a-1aa80a5f4099.png">

**Additional context**

**Comment by ami-aman** [comment]
Hi @alon7 

Thanks for reaching out.

Value of `push_enabled` depends upon the authorisation status of Push Notifications permission. As the user allows the push notification permissions later in the app, the status till then remains `push_enabled : "false"`.


I am curious to know, which library are you using to prompt push permissions at the later point in your app ?

**Comment by alon7** [comment]
@ami-aman I just realized that the FCM token is issued when the app is opened, so that's called `registerDeviceToken` immediately (even though APNS token is not available yet). There's no way for us to re-set the fcm token on customer io so the token is always push_enabled=false

**Comment by alon7** [comment]
@ami-aman just an update here -- Instead of listening to firebase's delegate, I exposed a native method that can set the token directly when we have it ready. Seems to be working fine. Would love to hear what you think about this solution

**Comment by lj-cio** [comment]
Hi @alon7, jumping in for @ami-aman to confirm that we just push version [2.0.1](https://github.com/customerio/customerio-reactnative/releases/tag/2.0.1) that gives you the flexibility to add a device token directly using the method `CustomerIO.registerDeviceToken(token)`.  Paired with the [custom device attributes](https://customer.io/docs/sdk/react-native/identify/#update-device) call, you should be able to set/override `push_enabled` Take a look?

**Comment by alon7** [comment]
Hi @lj-cio thanks! I just upgraded the lib and the `registerDeviceToken` works well (it's essentially what I did internally with our native module), but, thanks for supporting it. We're not using the custom device attributes yet but it might be helpful in the future

**Comment by lj-cio** [comment]
That's great to hear.  Thanks for confirming!
