### ISSUE TITLE
Call to customerio android SDK

### ISSUE THREAD

**Issue by matthieuMay** [customerio/customerio-reactnative#77]
Hi,

to allow some custom call to android SDK (and ensure to have the same versions used) it would be nice to replace implementation dependencies with api dependencies like this: 

```diff
diff --git a/node_modules/customerio-reactnative/android/cio-core.gradle b/node_modules/customerio-reactnative/android/cio-core.gradle
index 9c6dfbb..3d822c2 100644
--- a/node_modules/customerio-reactnative/android/cio-core.gradle
+++ b/node_modules/customerio-reactnative/android/cio-core.gradle
@@ -1,5 +1,5 @@
 dependencies {
-    implementation "io.customer.android:tracking:$cioAndroidSDKVersion"
-    implementation "io.customer.android:messaging-push-fcm:$cioAndroidSDKVersion"
-    implementation "io.customer.android:messaging-in-app:$cioAndroidSDKVersion"
+    api "io.customer.android:tracking:$cioAndroidSDKVersion"
+    api "io.customer.android:messaging-push-fcm:$cioAndroidSDKVersion"
+    api "io.customer.android:messaging-in-app:$cioAndroidSDKVersion"
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Shahroz16** [comment]
Hey @matthieuMay, thank you for the suggestion. We kept it as `implementation` to avoid confusion and bumping into the same problems that we have already resolved in our SDK packages. For example, the Android SDK lifecycle is different to the RN android app lifecycles, so in our SDK package we added a workaround for it, ultimately making the Android SDK lifecycle more flexible. So if anyone was to use Android SDK directly, they might have bumped into those issues as well. 

But we can consider it again and share our findings.

**Comment by matthieuMay** [comment]
I don't get the point here. 

You achieve the flexibility regarding the Android SDK version by providing the cioAndroidSDKVersion variable.

The api vs implementation is another topic. There are lots of implications on compile and runtime classpath but ultimately the question you should answer to know if you should use api or implementation is : do I want to allow the users of my library to be able to access the classes of the dependency.

In my application, I already have react-native-firebase/messaging (as I get notifications from other sources than customer.io). Therefore I needed to be able to call CustomerIOFirebaseMessagingService as explained here https://www.customer.io/docs/sdk/android/push/#set-up-push to have rich push notification working.

**Comment by mrehan27** [comment]
Hi @matthieuMay. Thanks for sharing the use-case. I understand your concern here. But a lot of React Native developers may not be very familiar with native code and may not want to play around it a lot, so we are not moving forward with the suggested changes for now at least.

The problem you shared is in our todo list to fix. Not very soon though, but we do have plans to add JS callbacks to overcome challenges with multiple notification services.

For now, to call native methods of Android SDK from your app, you can reintroduce Customer.io dependencies by adding following lines in `android/app/build.gradle` of your React Native app:

```
implementation "io.customer.android:tracking"
implementation "io.customer.android:messaging-push-fcm"
implementation "io.customer.android:messaging-in-app"
```

By dropping version number from the dependency, you can use the same version added by our React Native SDK and won't have to bump the version every time with newer release.

Please note that it may not work properly with some gradle tasks e.g. `androidDependencies`, but should still allow you to use SDK classes and compile the app. However, if your project needs to specify the version explicitly, you can add the version by reloading `gradle.properties` using the following snippet.

```
def cioSDKProperties = new Properties()
File cioSDKPropertiesFile = file("../../node_modules/customerio-reactnative/android/gradle.properties")
if (cioSDKPropertiesFile.isFile()) {
    cioSDKPropertiesFile.withInputStream { cioSDKProperties.load(it) }
} else {
    throw new GradleException('No gradle.properties found for Customer.io SDK')
}

def cioAndroidSDKVersion = cioSDKProperties['customerio.reactnative.cioSDKVersionAndroid']
implementation "io.customer.android:tracking:$cioAndroidSDKVersion"
implementation "io.customer.android:messaging-push-fcm:$cioAndroidSDKVersion"
implementation "io.customer.android:messaging-in-app:$cioAndroidSDKVersion"
```

**OR** If you want to completely rely on dependencies added by our SDK, you can use `apply from` instead

```
ext.cioAndroidSDKVersion = cioSDKProperties['customerio.reactnative.cioSDKVersionAndroid']
apply from: "../../node_modules/customerio-reactnative/android/cio-core.gradle"
```

Closing this issue for now, please feel free to post more queries if the suggestion doesn't work for you.
