### ISSUE TITLE
Add the Ability to Send Anonymous Events

### ISSUE THREAD

**Issue by vanenshi** [customerio/customerio-reactnative#81]
**Is your feature request related to a problem? Please describe.**

please add the ability to send anonymous events, which is available on the API [anonymous-events](https://www.customer.io/docs/anonymous-events/)

**Comment by vanenshi** [comment]
Well, our apps don't require a person to log in to use the app, so a person can use the app anonymously. if the user finds a house/roommate (our app is about finding roommates) suitable for him/her, they are most likely going to signup. we want to use the opportunity to for example send a coupon to the user, based on his anonymous activity.

**Comment by lj-cio** [comment]
Thanks for the quick response!  One more detail, for the coupon, how would it be delivered to the anonymous person?

**Comment by vanenshi** [comment]
Of course we are going to use the anonymous_id to like that data to person, when he/she sightedUp

Otherwise we could have just used a static identifier like "anon@domain.com" for all the anon users

**Comment by levibostian** [comment]
This feature request has been logged internally. Because of that, I will close this issue.

Anyone can feel free to comment on the issue if they have questions or comments.

**Comment by devontivona** [comment]
Hey folks, checking back in on this. This seems like a huge omission for customers who are using the Data Pipelines product. We use the Customer.io CDP to send data to downstream analytics sources (Mixpanel, etc.). 

Without the ability to log anonymous profiles and then merge them with identified profiles once a user authenticates, we're unable to measure perhaps the most important metric in our app: App Launch -> Sign In conversion. 

Tracking anonymous events and then associating them with a new account once authenticated seems like a table stakes feature of most other analytics platforms. 

Did we migrate from Segment to Customer.io Data Pipelines too soon? Is this product not mature enough to support a production use-case?

**Comment by devontivona** [comment]
Any update?

**Comment by levibostian** [comment]
Hey there, @devontivona. Thanks for asking.  

Thanks for letting us know the importance of this feature in your project. This request is on our roadmap for early this year, but at this time we can't share more than that in terms of timing. We appreciate the feedback as it helps us to prioritize this work.
