### ISSUE TITLE
[Android] Integrate with `@react-native-firebase/messaging`

### ISSUE THREAD

**Issue by vanenshi** [customerio/customerio-reactnative#84]
**SDK version:** 2.0.1

**Environment:** Development and Production

**Describe the bug**
in our application, we already add the `@react-native-firebase/messaging` for some custom use cases. 
we notice that rich push notifications (data-only) are not working on android. with more investigation, we notice 
that `@react-native-firebase/messaging` is overwriting the CustomerIO service, hence, there is no handler registered for the data-only push notification.
P.S: because of the CustomerIO `UNNotificationServiceExtension` in IOS,  rich push notifications are working properly

**To Reproduce**
1. create a react native app
2. initialize the FCM message using `@react-native-firebase/messaging` documents.
3. initialize the CustomerIO base on documents.
4. notification-only push notifications works, but data-only push notifications are not working (even though we know that they are delivered to the application by looking at the logs)
5. after removing the `@react-native-firebase/messaging` package, data-only push notifications work as expected

**Additional context**
I believe the problem can be solved by using a customer `FirebaseMessagingService` on android to support both CustomerIO and `@react-native-firebase/messaging` package.

**Comment by Shahroz16** [comment]
Hey, @vanenshi thank you for reaching out, we are aware of this, and we should probably document this too. If you are using any other push services, CIO integration might not work as we are intending to take over all the load from creating the token to handling the push and tracking ourselves.
This is a feature on our roadmap that we intend to get to in the next couple of releases.

**Comment by vanenshi** [comment]
Hi guys, is this issue getting closed by https://github.com/customerio/customerio-reactnative/pull/117?

**Comment by Shahroz16** [comment]
Hey @vanenshi, apologies for the delay and yes This issue is resolved now. You can check out the [docs](https://customer.io/docs/sdk/react-native/push/#cio-process-notification-payloads) for more information on it. 

RN-Firebase, will receive the `data` only payload and you can forward it to our SDK. Thanks for your patience.
