### ISSUE TITLE
CustomerIO.initialize() promise returns nothing

### ISSUE THREAD

**Issue by UsmanZulfi** [customerio/customerio-reactnative#86]
const env = new CustomerIOEnv()
            env.siteId = "siteId"
            env.apiKey = "apiKeyId"            
            const data = new CustomerioConfig()
            data.logLevel = CioLogLevel.debug
            data.autoTrackDeviceAttributes = true              
            CustomerIO.initialize(env, data).then((response)=> {
              console.log(response);
            }).catch((error)=> {
              console.log(error);
            }).
            
            promise returns nothing in response neither it returns any error.
            Anyone knows about that?

**Comment by mrehan27** [comment]
Hi @UsmanZulfi. I don't think we planned to return anything in promise for it. You should be able to use it synchronously [as suggested in the docs](https://www.customer.io/docs/sdk/react-native/getting-started/#initialize-the-sdk). If you have more questions, please let us know.

**Comment by UsmanZulfi** [comment]
> Hi @UsmanZulfi. I don't think we planned to return anything in promise for it. You should be able to use it synchronously [as suggested in the docs](https://www.customer.io/docs/sdk/react-native/getting-started/#initialize-the-sdk). If you have more questions, please let us know.

I created this issue because inside try catch, code break after this line (CustomerIO.initialize()) and returns an empty object as an error inside catch.

**Comment by mrehan27** [comment]
You do not need to receive anything when initializing. `CustomerIO.initialize(env, data)` should be enough to initialize the SDK.

If that still doesn't work, please share complete code snippet including the line throwing error, the error you are receiving and additional details like SDK Version, Platform, Additional Logs and any details that might help us identifying the issue.

**Comment by ami-aman** [comment]
Closing this issue. Feel free to reopen if needed.
